"""Seed questions: entertainment, tech, sports, fashion, nature, work, silly, general.
Format: {category_id: [(prompt, option1, option2), ...]}
"""

SEED = {
    "entertainment": [
        ("Marvel or DC?", "Marvel", "DC"),
        ("Star Wars or Star Trek?", "Star Wars", "Star Trek"),
        ("Harry Potter or Lord of the Rings?", "Harry Potter", "LOTR"),
        ("Batman or Spider-Man?", "Batman", "Spider-Man"),
        ("Superman or Wonder Woman?", "Superman", "Wonder Woman"),
        ("Breaking Bad or The Sopranos?", "Breaking Bad", "The Sopranos"),
        ("Friends or How I Met Your Mother?", "Friends", "HIMYM"),
        ("The Office or Parks and Recreation?", "The Office", "Parks and Rec"),
        ("Stranger Things or Dark?", "Stranger Things", "Dark"),
        ("Game of Thrones or The Witcher?", "GoT", "The Witcher"),
        ("Squid Game or Alice in Borderland?", "Squid Game", "Alice"),
        ("Money Heist or Peaky Blinders?", "Money Heist", "Peaky Blinders"),
        ("The Crown or Downton Abbey?", "The Crown", "Downton"),
        ("Sherlock or Lupin?", "Sherlock", "Lupin"),
        ("K-dramas or Turkish dramas?", "K-dramas", "Turkish dramas"),
        ("Anime or manga?", "Anime", "Manga"),
        ("Naruto or One Piece?", "Naruto", "One Piece"),
        ("Dragon Ball or Pokémon?", "Dragon Ball", "Pokémon"),
        ("Studio Ghibli or Pixar?", "Ghibli", "Pixar"),
        ("Toy Story or Shrek?", "Toy Story", "Shrek"),
        ("Frozen or Moana?", "Frozen", "Moana"),
        ("The Lion King or Aladdin?", "Lion King", "Aladdin"),
        ("Disney classics or Disney live-action?", "Classics", "Live-action"),
        ("Musicals or animated films?", "Musicals", "Animated"),
        ("La La Land or The Greatest Showman?", "La La Land", "Greatest Showman"),
        ("Horror films or psychological thrillers?", "Horror", "Thrillers"),
        ("The Conjuring or Insidious?", "Conjuring", "Insidious"),
        ("Zombie movies or vampire movies?", "Zombies", "Vampires"),
        ("Aliens or ghosts?", "Aliens", "Ghosts"),
        ("Found footage or traditional horror?", "Found footage", "Traditional"),
        ("Action franchises: Fast or Mission Impossible?", "Fast", "Mission Impossible"),
        ("James Bond or Jason Bourne?", "Bond", "Bourne"),
        ("John Wick or Taken?", "John Wick", "Taken"),
        ("Quentin Tarantino or Christopher Nolan?", "Tarantino", "Nolan"),
        ("Spielberg or Scorsese?", "Spielberg", "Scorsese"),
        ("Inception or Interstellar?", "Inception", "Interstellar"),
        ("The Matrix or Blade Runner?", "Matrix", "Blade Runner"),
        ("Dune or Arrival?", "Dune", "Arrival"),
        ("Oppenheimer or Barbie?", "Oppenheimer", "Barbie"),
        ("Rom-coms or tearjerkers?", "Rom-coms", "Tearjerkers"),
        ("The Notebook or La La Land ending?", "The Notebook", "La La Land"),
        ("Titanic or The Titanic documentary?", "Titanic", "Documentary"),
        ("Sitcoms or dramedies?", "Sitcoms", "Dramedies"),
        ("Reality dating shows or reality survival shows?", "Dating", "Survival"),
        ("Love Island or Bachelor Nation?", "Love Island", "Bachelor"),
        ("Cooking competitions or baking competitions?", "Cooking", "Baking"),
        ("The Great British Bake Off or MasterChef?", "Bake Off", "MasterChef"),
        ("RuPaul's Drag Race or America's Got Talent?", "Drag Race", "AGT"),
        ("Survivor or The Amazing Race?", "Survivor", "Amazing Race"),
        ("Talk shows or late-night comedy?", "Talk shows", "Late-night"),
        ("Podcasts: interview or storytelling?", "Interview", "Storytelling"),
        ("True crime podcasts or comedy podcasts?", "True crime", "Comedy"),
        ("Serial or This American Life?", "Serial", "TAL"),
        ("Audiobooks narrated by authors or actors?", "Authors", "Actors"),
        ("Music: oldies or current hits?", "Oldies", "Current"),
        ("Vinyl records or digital streaming?", "Vinyl", "Streaming"),
        ("Cassettes or CDs?", "Cassettes", "CDs"),
        ("Pop or rock?", "Pop", "Rock"),
        ("Hip-hop or R&B?", "Hip-hop", "R&B"),
        ("Country or folk?", "Country", "Folk"),
        ("Jazz or blues?", "Jazz", "Blues"),
        ("Classical or lo-fi?", "Classical", "Lo-fi"),
        ("EDM or house?", "EDM", "House"),
        ("Reggaeton or Afrobeat?", "Reggaeton", "Afrobeat"),
        ("K-pop or J-pop?", "K-pop", "J-pop"),
        ("Beyoncé or Rihanna?", "Beyoncé", "Rihanna"),
        ("Taylor Swift or Adele?", "Taylor Swift", "Adele"),
        ("Drake or Kendrick?", "Drake", "Kendrick"),
        ("The Beatles or The Rolling Stones?", "Beatles", "Stones"),
        ("Queen or ABBA?", "Queen", "ABBA"),
        ("Michael Jackson or Prince?", "MJ", "Prince"),
        ("Elvis or Sinatra?", "Elvis", "Sinatra"),
        ("Nirvana or Pearl Jam?", "Nirvana", "Pearl Jam"),
        ("Concerts small venue or stadium?", "Small venue", "Stadium"),
        ("Music festivals one-day or full weekend?", "One day", "Full weekend"),
        ("Front row at a concert or backstage pass?", "Front row", "Backstage"),
        ("Karaoke classic rock or karaoke pop?", "Rock", "Pop"),
        ("Dance like nobody's watching or watch everybody dance?", "Dance", "Watch"),
        ("Music videos or lyric videos?", "Music videos", "Lyric videos"),
        ("Albums front to back or shuffle everything?", "Front to back", "Shuffle"),
        ("Radio or personal playlist?", "Radio", "Playlist"),
        ("Video games: story mode or multiplayer?", "Story mode", "Multiplayer"),
        ("Mario or Zelda?", "Mario", "Zelda"),
        ("PlayStation or Xbox?", "PlayStation", "Xbox"),
        ("Nintendo Switch or Steam Deck?", "Switch", "Steam Deck"),
        ("Minecraft or Roblox?", "Minecraft", "Roblox"),
        ("Fortnite or Call of Duty?", "Fortnite", "CoD"),
        ("FIFA or NBA 2K?", "FIFA", "NBA 2K"),
        ("Chess or checkers?", "Chess", "Checkers"),
        ("Monopoly or Risk?", "Monopoly", "Risk"),
        ("Scrabble or Wordle?", "Scrabble", "Wordle"),
        ("Catan or Ticket to Ride?", "Catan", "Ticket to Ride"),
        ("Cards Against Humanity or Charades?", "CAH", "Charades"),
        ("Poker night or blackjack night?", "Poker", "Blackjack"),
        ("Trivia: general knowledge or pop culture?", "General", "Pop culture"),
        ("Escape rooms: horror themed or mystery themed?", "Horror", "Mystery"),
        ("Improv show or stand-up show?", "Improv", "Stand-up"),
        ("Circus or magic show?", "Circus", "Magic"),
        ("Drive-in revival or IMAX experience?", "Drive-in", "IMAX"),
        ("Film festivals or premiere nights?", "Festivals", "Premieres"),
        ("Watch the trailer or go in blind?", "Trailer", "Blind"),
        ("Read the book first or watch first?", "Book first", "Watch first"),
        ("Subtitles for foreign films or dubs?", "Subtitles", "Dubs"),
        ("Series finale: satisfying or controversial?", "Satisfying", "Controversial"),
        ("Binge now or savor weekly?", "Binge", "Weekly"),
        ("Spoiler alerts respected or spoilers welcome?", "Respected", "Welcome"),
        ("Watch parties or solo viewing?", "Watch parties", "Solo"),
        ("Awards shows watched live or recapped after?", "Live", "Recap"),
        ("Oscars best picture: popular or artsy?", "Popular", "Artsy"),
        ("Reboots welcome or leave the classics?", "Reboots", "Leave classics"),
        ("Streaming password shared or private?", "Shared", "Private"),
        ("Cancel subscriptions often or keep them all?", "Cancel often", "Keep all"),
        ("One more episode or sleep?", "One more", "Sleep"),
    ],

    "technology": [
        ("Face ID or fingerprint?", "Face ID", "Fingerprint"),
        ("Phone notifications batched or instant?", "Batched", "Instant"),
        ("Dark mode or light mode forever?", "Dark", "Light"),
        ("One monitor or dual monitors?", "One", "Dual"),
        ("Mechanical keyboard or membrane?", "Mechanical", "Membrane"),
        ("Mouse or trackpad?", "Mouse", "Trackpad"),
        ("Laptop stickers or clean lid?", "Stickers", "Clean"),
        ("Phone case rugged or minimal?", "Rugged", "Minimal"),
        ("Screen protector or naked screen?", "Protector", "Naked"),
        ("Wireless charging or fast cable?", "Wireless", "Fast cable"),
        ("Battery saver always or full brightness?", "Battery saver", "Full bright"),
        ("Phone upgrade yearly or ride it out?", "Yearly", "Ride it out"),
        ("Android customization or iPhone simplicity?", "Customization", "Simplicity"),
        ("Google ecosystem or Apple ecosystem?", "Google", "Apple"),
        ("Smartwatch or fitness band?", "Smartwatch", "Fitness band"),
        ("Smart speaker in every room or none?", "Every room", "None"),
        ("Smart doorbell or smart lock?", "Doorbell", "Lock"),
        ("Smart lights or smart thermostat first?", "Lights", "Thermostat"),
        ("Robot vacuum or robot mop?", "Vacuum", "Mop"),
        ("TV streaming stick or smart TV apps?", "Stick", "Smart TV"),
        ("Noise cancelling or transparency mode?", "Noise cancelling", "Transparency"),
        ("Earbuds or over-ear headphones?", "Earbuds", "Over-ear"),
        ("Bone conduction or traditional headphones?", "Bone conduction", "Traditional"),
        ("Voice typing or thumb typing?", "Voice", "Thumb"),
        ("GIF replies or emoji replies?", "GIFs", "Emoji"),
        ("Emoji reactions or text replies?", "Reactions", "Text"),
        ("Emoji: classics or new designs?", "Classics", "New designs"),
        ("Video messages or voice notes?", "Video", "Voice notes"),
        ("Group chats active or muted?", "Active", "Muted"),
        ("Zoom happy hours or in-person?", "Zoom", "In person"),
        ("Cloud backup or external drive?", "Cloud", "External drive"),
        ("NAS at home or cloud storage?", "NAS", "Cloud"),
        ("Password manager or memory?", "Manager", "Memory"),
        ("Two-factor everywhere or convenience first?", "Everywhere", "Convenience"),
        ("Password resets often or one forever?", "Often", "One forever"),
        ("VPN always on or public wifi courage?", "VPN", "Courage"),
        ("Ad blocker or support the sites?", "Ad block", "Support sites"),
        ("Cookies accepted or rejected?", "Accept all", "Reject"),
        ("Incognito mode regular or rare?", "Regular", "Rare"),
        ("Social media cleanse quarterly or never?", "Quarterly", "Never"),
        ("Doom scrolling at night or disciplined?", "Doom scroll", "Disciplined"),
        ("AI assistant for questions or search engine?", "AI assistant", "Search"),
        ("AI writing help or your own words?", "AI help", "Own words"),
        ("AI art impressive or unsettling?", "Impressive", "Unsettling"),
        ("Self-driving cars exciting or scary?", "Exciting", "Scary"),
        ("Drone photography or ground photography?", "Drone", "Ground"),
        ("VR headsets or AR glasses?", "VR", "AR"),
        ("Metaverse curiosity or metaverse skepticism?", "Curiosity", "Skepticism"),
        ("Crypto believer or crypto skeptic?", "Believer", "Skeptic"),
        ("NFTs art or NFTs scam?", "Art", "Scam"),
        ("Terminal commands or GUI clicks?", "Terminal", "GUI"),
        ("Linux or Windows daily?", "Linux", "Windows"),
        ("Open source loyalty or best tool wins?", "Open source", "Best tool"),
        ("Coding as hobby or coding as career?", "Hobby", "Career"),
        ("Build your PC or buy prebuilt?", "Build", "Prebuilt"),
        ("Cable management obsessed or spaghetti desk?", "Obsessed", "Spaghetti"),
        ("Standing desk converter or full desk?", "Converter", "Full desk"),
        ("Ergonomic chair or gaming chair?", "Ergonomic", "Gaming"),
        ("Desk plants or desk gadgets?", "Plants", "Gadgets"),
        ("Digital minimalism or app abundance?", "Minimalism", "Abundance"),
        ("Folder organization or search everything?", "Folders", "Search"),
        ("Desktop icons everywhere or clean desktop?", "Everywhere", "Clean"),
        ("Email folders or inbox search?", "Folders", "Search"),
        ("Tablet as laptop replacement or companion?", "Replacement", "Companion"),
        ("E-reader or tablet for reading?", "E-reader", "Tablet"),
        ("Smart home privacy concerns or convenience wins?", "Privacy", "Convenience"),
        ("Tech early adopter or late majority?", "Early", "Late"),
    ],

    "sports": [
        ("Football or basketball to watch?", "Football", "Basketball"),
        ("Tennis or golf to play?", "Tennis", "Golf"),
        ("Individual sports or team sports?", "Individual", "Team"),
        ("Summer Olympics or Winter Olympics?", "Summer", "Winter"),
        ("World Cup or Champions League?", "World Cup", "Champions League"),
        ("Premier League or La Liga?", "Premier League", "La Liga"),
        ("Messi or Ronaldo?", "Messi", "Ronaldo"),
        ("LeBron or Jordan?", "LeBron", "Jordan"),
        ("Kobe or Shaq?", "Kobe", "Shaq"),
        ("Federer or Nadal?", "Federer", "Nadal"),
        ("Djokovic or the field?", "Djokovic", "The field"),
        ("Serena or Venus?", "Serena", "Venus"),
        ("F1 or MotoGP?", "F1", "MotoGP"),
        ("Hamilton or Verstappen?", "Hamilton", "Verstappen"),
        ("Le Mans or Monaco GP?", "Le Mans", "Monaco"),
        ("Rally racing or circuit racing?", "Rally", "Circuit"),
        ("Boxing or MMA?", "Boxing", "MMA"),
        ("UFC or bellator?", "UFC", "Bellator"),
        ("Cricket or baseball?", "Cricket", "Baseball"),
        ("T20 or test cricket?", "T20", "Test"),
        ("Rugby or American football?", "Rugby", "American football"),
        ("Swimming or athletics?", "Swimming", "Athletics"),
        ("Sprinting or marathon?", "Sprinting", "Marathon"),
        ("Triathlon or ultramarathon?", "Triathlon", "Ultra"),
        ("Cycling road or mountain?", "Road", "Mountain"),
        ("Skateboarding or BMX?", "Skate", "BMX"),
        ("Snowboarding or skiing?", "Snowboarding", "Skiing"),
        ("Surfing or windsurfing?", "Surfing", "Windsurfing"),
        ("Rock climbing indoor or outdoor?", "Indoor", "Outdoor"),
        ("Bouldering or top rope?", "Bouldering", "Top rope"),
        ("Parkour or freerunning?", "Parkour", "Freerunning"),
        ("Martial arts: karate or judo?", "Karate", "Judo"),
        ("Taekwondo or kickboxing?", "Taekwondo", "Kickboxing"),
        ("Yoga as sport or yoga as practice?", "Sport", "Practice"),
        ("Pilates reformer or mat?", "Reformer", "Mat"),
        ("CrossFit or traditional gym?", "CrossFit", "Traditional"),
        ("HIIT or steady state cardio?", "HIIT", "Steady state"),
        ("Free weights or machines?", "Free weights", "Machines"),
        ("Deadlift or squat PR?", "Deadlift", "Squat"),
        ("Push-ups or pull-ups?", "Push-ups", "Pull-ups"),
        ("Plank challenge or burpee challenge?", "Plank", "Burpees"),
        ("Treadmill or elliptical?", "Treadmill", "Elliptical"),
        ("Spin class or solo ride?", "Spin class", "Solo"),
        ("Run with music or run with podcasts?", "Music", "Podcasts"),
        ("Morning run or evening run?", "Morning", "Evening"),
        ("Run outdoors or run indoors?", "Outdoors", "Indoors"),
        ("5K speed or marathon endurance?", "5K speed", "Marathon"),
        ("Race for the medal or race for the vibe?", "Medal", "Vibe"),
        ("Fantasy sports league or no thanks?", "Yes", "No thanks"),
        ("Sports radio or sports podcasts?", "Radio", "Podcasts"),
        ("Watch at the stadium or at the bar?", "Stadium", "Bar"),
        ("Season tickets or pick and choose?", "Season tickets", "Pick and choose"),
        ("Jersey wearing or subtle support?", "Jersey", "Subtle"),
        ("Play in a rec league or watch only?", "Rec league", "Watch only"),
        ("Ping pong or foosball?", "Ping pong", "Foosball"),
        ("Darts or pool?", "Darts", "Pool"),
        ("Bowling league or casual bowling?", "League", "Casual"),
        ("Air hockey or arcade basketball?", "Air hockey", "Arcade hoops"),
        ("Trampoline parks or obstacle courses?", "Trampoline", "Obstacles"),
        ("Paintball or airsoft?", "Paintball", "Airsoft"),
        ("Laser tag or escape rooms?", "Laser tag", "Escape rooms"),
        ("Go-karting indoor or outdoor?", "Indoor", "Outdoor"),
        ("Betting on the game or friendly wagers?", "Betting", "Friendly"),
        ("Sports documentaries or highlight reels?", "Documentaries", "Highlights"),
        ("Rivalry games or finals games?", "Rivalries", "Finals"),
        ("Underdog story or dynasty story?", "Underdog", "Dynasty"),
        ("Overtime thrillers or blowouts?", "Overtime", "Blowouts"),
        ("Stats and analytics or eye test?", "Analytics", "Eye test"),
        ("Live score alerts or check later?", "Alerts", "Later"),
    ],

    "fashion": [
        ("Sneakers with everything or boots with everything?", "Sneakers", "Boots"),
        ("White sneakers or colorful sneakers?", "White", "Colorful"),
        ("High tops or low tops?", "High tops", "Low tops"),
        ("Loafers or brogues?", "Loafers", "Brogues"),
        ("Sandals summer or slides summer?", "Sandals", "Slides"),
        ("Flip-flops vacation or barefoot vacation?", "Flip-flops", "Barefoot"),
        ("Heels or flats for events?", "Heels", "Flats"),
        ("Stilettos or block heels?", "Stilettos", "Block heels"),
        ("Ankle boots or knee-high boots?", "Ankle", "Knee-high"),
        ("Leather jacket or denim jacket?", "Leather", "Denim"),
        ("Blazer or cardigan?", "Blazer", "Cardigan"),
        ("Hoodies or sweaters?", "Hoodies", "Sweaters"),
        ("Turtlenecks or V-necks?", "Turtlenecks", "V-necks"),
        ("Crewnecks or collared shirts?", "Crewnecks", "Collars"),
        ("Oversized fit or tailored fit?", "Oversized", "Tailored"),
        ("Slim fit or straight fit?", "Slim", "Straight"),
        ("Athleisure all day or dressed up all day?", "Athleisure", "Dressed up"),
        ("Monochrome outfits or colorful outfits?", "Monochrome", "Colorful"),
        ("Neutrals wardrobe or rainbow wardrobe?", "Neutrals", "Rainbow"),
        ("Pastels or jewel tones?", "Pastels", "Jewel tones"),
        ("Earth tones or neon pops?", "Earth tones", "Neon"),
        ("Animal print or metallics?", "Animal print", "Metallics"),
        ("Stripes or polka dots?", "Stripes", "Polka dots"),
        ("Plaid or floral?", "Plaid", "Floral"),
        ("Camouflage or tie-dye?", "Camo", "Tie-dye"),
        ("Black tie events or smart casual events?", "Black tie", "Smart casual"),
        ("Suit and tie or suit no tie?", "Tie", "No tie"),
        ("Dress or pants for formal events?", "Dress", "Pants"),
        ("Maxi dresses or mini dresses?", "Maxi", "Mini"),
        ("Midi skirts or pleated skirts?", "Midi", "Pleated"),
        ("Wide-leg pants or skinny pants?", "Wide-leg", "Skinny"),
        ("Cargo pants or joggers?", "Cargo", "Joggers"),
        ("Jeans: light wash or dark wash?", "Light wash", "Dark wash"),
        ("Distressed denim or clean denim?", "Distressed", "Clean"),
        ("Raw denim or stretch denim?", "Raw", "Stretch"),
        ("Shorts summer or pants summer?", "Shorts", "Pants"),
        ("Swim trunks or swim briefs?", "Trunks", "Briefs"),
        ("One-piece swimsuit or two-piece?", "One-piece", "Two-piece"),
        ("Accessories: gold or silver?", "Gold", "Silver"),
        ("Layered necklaces or statement necklace?", "Layered", "Statement"),
        ("Hoops or studs?", "Hoops", "Studs"),
        ("Watches: analog or digital?", "Analog", "Digital"),
        ("Smartwatch dressed up or hidden?", "Dressed up", "Hidden"),
        ("Bracelets or rings?", "Bracelets", "Rings"),
        ("Stacked rings or single ring?", "Stacked", "Single"),
        ("Hats: baseball cap or beanie?", "Baseball cap", "Beanie"),
        ("Bucket hats or fedoras?", "Bucket", "Fedora"),
        ("Sun hats or visors?", "Sun hat", "Visor"),
        ("Scarves or shawls?", "Scarves", "Shawls"),
        ("Sunglasses: aviators or wayfarers?", "Aviators", "Wayfarers"),
        ("Round frames or rectangular frames?", "Round", "Rectangular"),
        ("Clear lenses or tinted lenses?", "Clear", "Tinted"),
        ("Glasses or contacts?", "Glasses", "Contacts"),
        ("Belts or beltless?", "Belts", "Beltless"),
        ("Bags: crossbody or backpack?", "Crossbody", "Backpack"),
        ("Tote bags or shoulder bags?", "Tote", "Shoulder"),
        ("Clutch for nights out or mini backpack?", "Clutch", "Mini backpack"),
        ("Wallet slim or wallet chunky?", "Slim", "Chunky"),
        ("Shopping: sale racks or full price?", "Sale racks", "Full price"),
        ("Seasonal wardrobe refresh or capsule wardrobe?", "Refresh", "Capsule"),
    ],

    "nature": [
        ("Ocean waves or mountain echoes?", "Waves", "Echoes"),
        ("Forest walk or meadow stroll?", "Forest", "Meadow"),
        ("Waterfalls or hot springs?", "Waterfalls", "Hot springs"),
        ("Caves or canyons?", "Caves", "Canyons"),
        ("Desert dunes or red rock cliffs?", "Dunes", "Red rocks"),
        ("Arctic tundra or tropical jungle?", "Arctic", "Jungle"),
        ("Coral reefs or kelp forests?", "Coral", "Kelp"),
        ("Northern lights or midnight sun?", "Aurora", "Midnight sun"),
        ("Thunderstorms or snowstorms?", "Thunder", "Snow"),
        ("Summer rain or winter frost?", "Summer rain", "Winter frost"),
        ("Autumn leaves or spring blossoms?", "Autumn", "Spring"),
        ("Cherry blossoms or lavender fields?", "Cherry", "Lavender"),
        ("Sunflower fields or poppy fields?", "Sunflowers", "Poppies"),
        ("Wildflower meadows or manicured gardens?", "Wildflowers", "Gardens"),
        ("Bamboo forest or pine forest?", "Bamboo", "Pine"),
        ("Oak trees or willow trees?", "Oak", "Willow"),
        ("Cacti or succulents?", "Cacti", "Succulents"),
        ("Bonsai or terrariums?", "Bonsai", "Terrarium"),
        ("Mushroom foraging or berry picking?", "Mushrooms", "Berries"),
        ("Birdwatching dawn or birdwatching dusk?", "Dawn", "Dusk"),
        ("Owls or eagles?", "Owls", "Eagles"),
        ("Penguins or puffins?", "Penguins", "Puffins"),
        ("Flamingos or peacocks?", "Flamingos", "Peacocks"),
        ("Parrots or cockatoos?", "Parrots", "Cockatoos"),
        ("Hummingbirds or butterflies?", "Hummingbirds", "Butterflies"),
        ("Fireflies or glowworms?", "Fireflies", "Glowworms"),
        ("Ladybugs or dragonflies?", "Ladybugs", "Dragonflies"),
        ("Bees or ants as neighbors?", "Bees", "Ants"),
        ("Horses or deer?", "Horses", "Deer"),
        ("Foxes or wolves?", "Foxes", "Wolves"),
        ("Bears or moose?", "Bears", "Moose"),
        ("Rabbits or squirrels?", "Rabbits", "Squirrels"),
        ("Hedgehogs or otters?", "Hedgehogs", "Otters"),
        ("Pandas or koalas?", "Pandas", "Koalas"),
        ("Sloths or lemurs?", "Sloths", "Lemurs"),
        ("Elephants or giraffes?", "Elephants", "Giraffes"),
        ("Lions or tigers?", "Lions", "Tigers"),
        ("Leopards or cheetahs?", "Leopards", "Cheetahs"),
        ("Whale watching or dolphin watching?", "Whales", "Dolphins"),
        ("Sea turtles or seals?", "Turtles", "Seals"),
        ("Octopuses or seahorses?", "Octopuses", "Seahorses"),
        ("Jellyfish or starfish?", "Jellyfish", "Starfish"),
        ("Sharks or rays?", "Sharks", "Rays"),
        ("Coral or pearls?", "Coral", "Pearls"),
        ("Seashell collecting or rock collecting?", "Shells", "Rocks"),
        ("Skipping stones or building sandcastles?", "Skipping stones", "Sandcastles"),
        ("Stargazing or moon watching?", "Stars", "Moon"),
        ("Full moon or crescent moon?", "Full", "Crescent"),
        ("Meteor showers or eclipses?", "Meteors", "Eclipses"),
        ("Sunrise hikes or sunset picnics?", "Sunrise hikes", "Sunset picnics"),
        ("Camping in forests or camping by lakes?", "Forests", "Lakes"),
        ("Hammock between trees or tent under stars?", "Hammock", "Tent"),
        ("Fishing or foraging?", "Fishing", "Foraging"),
        ("Kayaking rivers or kayaking lakes?", "Rivers", "Lakes"),
        ("Snorkeling shallow reefs or deep dives?", "Shallow", "Deep"),
        ("Surfing morning or swimming midnight?", "Morning surf", "Midnight swim"),
        ("Gardening flowers or vegetables?", "Flowers", "Vegetables"),
        ("Composting or rainwater collecting?", "Compost", "Rainwater"),
        ("National parks or nature reserves?", "National parks", "Reserves"),
        ("Zoos or sanctuaries?", "Zoos", "Sanctuaries"),
        ("Pets: adopted or rescued?", "Adopted", "Rescued"),
        ("Dogs off-leash beaches or dogs on trails?", "Beaches", "Trails"),
        ("Cats indoor or cats outdoor?", "Indoor", "Outdoor"),
    ],

    "work": [
        ("Email first thing or email after lunch?", "First thing", "After lunch"),
        ("Inbox zero or inbox archive-all?", "Zero", "Archive all"),
        ("Meetings in the morning or afternoons?", "Morning", "Afternoon"),
        ("Camera on or camera off?", "On", "Off"),
        ("Video calls or audio calls?", "Video", "Audio"),
        ("Stand-up meetings or async updates?", "Stand-up", "Async"),
        ("Brainstorms in groups or solo first?", "Group", "Solo first"),
        ("Open office or remote forever?", "Open office", "Remote"),
        ("Hybrid week or fully onsite?", "Hybrid", "Onsite"),
        ("Home office or coworking space?", "Home", "Coworking"),
        ("Coffee shop working or library working?", "Coffee shop", "Library"),
        ("Commute by car or public transport?", "Car", "Public transport"),
        ("Commute podcast or commute silence?", "Podcast", "Silence"),
        ("Flexible hours or set schedule?", "Flexible", "Set"),
        ("Four-day week or five-day week?", "Four-day", "Five-day"),
        ("Early shifts or late shifts?", "Early", "Late"),
        ("Overtime for money or overtime never?", "For money", "Never"),
        ("Salary or equity?", "Salary", "Equity"),
        ("Bonus or raise?", "Bonus", "Raise"),
        ("Title bump or pay bump?", "Title", "Pay"),
        ("Big company or small startup?", "Big company", "Startup"),
        ("Corporate structure or flat hierarchy?", "Corporate", "Flat"),
        ("Known company or exciting unknown?", "Known", "Unknown"),
        ("Manager track or expert track?", "Manager", "Expert"),
        ("Lead the team or mentor quietly?", "Lead", "Mentor"),
        ("Delegate or do it yourself?", "Delegate", "DIY"),
        ("Perfection shipped late or good shipped now?", "Perfect and late", "Good now"),
        ("Deep work blocks or reactive flow?", "Deep blocks", "Reactive"),
        ("Music while working or silence?", "Music", "Silence"),
        ("Desk plants or desk photos?", "Plants", "Photos"),
        ("Sticky notes or digital boards?", "Sticky notes", "Digital boards"),
        ("To-do list apps or a simple notebook?", "Apps", "Notebook"),
        ("Time blocking or task batching?", "Time blocking", "Batching"),
        ("Pomodoro sprints or natural rhythm?", "Pomodoro", "Natural rhythm"),
        ("Monday planning or Sunday planning?", "Monday", "Sunday"),
        ("Friday wrap-ups or Friday coasting?", "Wrap-up", "Coast"),
        ("Workations or proper vacations?", "Workations", "Proper vacations"),
        ("Unplug on vacation or check in?", "Unplug", "Check in"),
        ("Sick day: rest or work from bed?", "Rest", "Work from bed"),
        ("Feedback direct or feedback sandwiched?", "Direct", "Sandwiched"),
        ("Performance reviews or continuous feedback?", "Reviews", "Continuous"),
        ("Public praise or private praise?", "Public", "Private"),
        ("Constructive criticism or compliments first?", "Criticism", "Compliments"),
        ("Networking events or one-on-ones?", "Events", "One-on-ones"),
        ("LinkedIn active or LinkedIn dormant?", "Active", "Dormant"),
        ("Business cards or QR codes?", "Cards", "QR codes"),
        ("Work friends or professional distance?", "Friends", "Distance"),
        ("Office gossip or office silence?", "Gossip", "Silence"),
        ("Office parties: attend or escape?", "Attend", "Escape"),
        ("Team lunches or solo lunches?", "Team", "Solo"),
        ("Lunch walks or lunch naps?", "Walks", "Naps"),
        ("Coffee machine chats or quick exits?", "Chats", "Exits"),
        ("Dress to impress or dress for comfort?", "Impress", "Comfort"),
        ("Casual Friday every day or dressed up daily?", "Casual daily", "Dressed up"),
        ("Learning budget or conference budget?", "Learning", "Conferences"),
        ("Certifications or experience?", "Certifications", "Experience"),
        ("Side projects allowed or focused role?", "Side projects", "Focused"),
        ("Job hopping or long tenure?", "Hopping", "Tenure"),
        ("Resign in person or resignation letter?", "In person", "Letter"),
        ("Interviews honest or interviews polished?", "Honest", "Polished"),
        ("Dream company or dream role?", "Company", "Role"),
        ("Passion project or paying the bills?", "Passion", "Bills"),
        ("Retire early or never retire?", "Early", "Never"),
    ],

    "silly-fun": [
        ("Pineapple on pizza: yes or crime?", "Yes", "Crime"),
        ("Cilantro: delicious or soap?", "Delicious", "Soap"),
        ("Hot dogs are sandwiches: yes or no?", "Yes", "No"),
        ("Cereal first or milk first?", "Cereal", "Milk"),
        ("Soup is a drink: agree or disagree?", "Agree", "Disagree"),
        ("Toast: butter side up or butter side down?", "Up", "Down"),
        ("Pizza crust: eat it or leave it?", "Eat it", "Leave it"),
        ("Pizza folded or flat?", "Folded", "Flat"),
        ("Burgers with fork or with hands?", "Fork", "Hands"),
        ("Fries dipped in milkshake: genius or weird?", "Genius", "Weird"),
        ("Ketchup in the fridge or the pantry?", "Fridge", "Pantry"),
        ("Chocolate stash hidden or shared?", "Hidden", "Shared"),
        ("Last slice offered or claimed?", "Offered", "Claimed"),
        ("Gif pronounced 'jif' or 'gif'?", "Jif", "Gif"),
        ("Emoji or emoticons?", "Emoji", "Emoticons"),
        ("Autocorrect trusted or double-checked?", "Trusted", "Double-checked"),
        ("Voice-to-text in public: fine or embarrassing?", "Fine", "Embarrassing"),
        ("Group chat name: creative or default?", "Creative", "Default"),
        ("Read receipts on or off?", "On", "Off"),
        ("Typing indicators: pressure or useful?", "Pressure", "Useful"),
        ("Reply with memes or with words?", "Memes", "Words"),
        ("Pet cameras checked hourly or never?", "Hourly", "Never"),
        ("Talk to your pet like a person or normally?", "Like a person", "Normally"),
        ("Name your car or never?", "Name it", "Never"),
        ("Ice cream for breakfast: acceptable or outrageous?", "Acceptable", "Outrageous"),
        ("Cake for breakfast: same question?", "Acceptable", "Outrageous"),
        ("Socks with sandals: fashion crime or comfort win?", "Crime", "Comfort win"),
        ("Crocs in public: yes or no?", "Yes", "No"),
        ("Pajamas all day on Sundays: yes or no?", "Yes", "No"),
        ("Matching pajamas for the family: cute or too much?", "Cute", "Too much"),
        ("Halloween candy: hand out or keep?", "Hand out", "Keep"),
        ("Doorbell on Halloween: answer or hide?", "Answer", "Hide"),
        ("Decorations up in October or November?", "October", "November"),
        ("Christmas music before December: yes or no?", "Yes", "No"),
        ("White elephant gifts: funny or useful?", "Funny", "Useful"),
        ("Birthday spankings: tradition or skip?", "Tradition", "Skip"),
        ("Birthday cake: corner piece or center piece?", "Corner", "Center"),
        ("Frosting or cake part?", "Frosting", "Cake"),
        ("Cupcakes or muffins?", "Cupcakes", "Muffins"),
        ("Waffles as dessert or breakfast?", "Dessert", "Breakfast"),
        ("Beach sand: love or hate?", "Love", "Hate"),
        ("Pool noodles: fun or foam menace?", "Fun", "Menace"),
        ("Water balloon fights or squirt gun fights?", "Balloons", "Squirt guns"),
        ("Trampolines: childhood dream or injury trap?", "Dream", "Trap"),
        ("Rollercoasters: front car or back car?", "Front", "Back"),
        ("Haunting mazes or hayrides?", "Mazes", "Hayrides"),
        ("Clowns: funny or terrifying?", "Funny", "Terrifying"),
        ("Dolls: charming or creepy?", "Charming", "Creepy"),
        ("Mannequins at night: fine or unsettling?", "Fine", "Unsettling"),
        ("Siri listening: convenient or creepy?", "Convenient", "Creepy"),
        ("Robot vacuum names: yes or unnecessary?", "Yes", "Unnecessary"),
        ("Karaoke sober: brave or wild?", "Brave", "Wild"),
        ("Dancing at weddings: mandatory or optional?", "Mandatory", "Optional"),
        ("Wedding chicken or wedding fish?", "Chicken", "Fish"),
        ("Open bars: highlight or chaos?", "Highlight", "Chaos"),
        ("Party games: icebreakers or cringe?", "Icebreakers", "Cringe"),
        ("Small talk: enjoy or endure?", "Enjoy", "Endure"),
        ("Elevators: chat or silence?", "Chat", "Silence"),
        ("Plane seatmates: conversational or invisible?", "Conversational", "Invisible"),
        ("Superhero or supervillain?", "Hero", "Villain"),
        ("Invisibility or flying?", "Invisibility", "Flying"),
        ("Time travel to the past or the future?", "Past", "Future"),
        ("Mind reading or teleportation?", "Mind reading", "Teleportation"),
        ("Unlimited money or unlimited wishes?", "Money", "Wishes"),
        ("Live without music or without movies?", "No music", "No movies"),
        ("Live without coffee or without dessert?", "No coffee", "No dessert"),
        ("Lose your phone or your keys?", "Phone", "Keys"),
        ("Always be 10 minutes late or 20 minutes early?", "Late", "Early"),
        ("Know the date of your death or the cause?", "Date", "Cause"),
        ("Speak every language or talk to animals?", "Languages", "Animals"),
        ("Be a famous actor or a famous musician?", "Actor", "Musician"),
        ("Live in space or under the sea?", "Space", "Sea"),
        ("Have a rewind button or a pause button?", "Rewind", "Pause"),
        ("One wish now or three wishes in ten years?", "One now", "Three later"),
        ("Werewolf or vampire?", "Werewolf", "Vampire"),
        ("Zombie apocalypse: fight or hide?", "Fight", "Hide"),
        ("Survive on pizza or survive on tacos?", "Pizza", "Tacos"),
        ("Always whisper or always shout?", "Whisper", "Shout"),
        ("Sneeze forever or hiccup forever?", "Sneeze", "Hiccup"),
        ("Hands for feet or feet for hands?", "Hands for feet", "Feet for hands"),
        ("Hair like a mop or hair like spaghetti?", "Mop", "Spaghetti"),
        ("Burp glitter or cry glitter?", "Burp", "Cry"),
        ("Slow internet or low battery forever?", "Slow internet", "Low battery"),
        ("Spiders the size of cats or cats the size of spiders?", "Giant spiders", "Spider cats"),
        ("Eat the same meal forever or never repeat a meal?", "Same forever", "Never repeat"),
        ("Sleep 12 hours once a week or 5 hours nightly?", "12 once", "5 nightly"),
        ("Toilet paper over or under?", "Over", "Under"),
        ("Toothpaste: squeeze from the middle or the end?", "Middle", "End"),
        ("Dishes left overnight: acceptable or scandalous?", "Acceptable", "Scandalous"),
        ("Making the bed daily: essential or pointless?", "Essential", "Pointless"),
        ("Passenger seat DJ or driver picks?", "Passenger", "Driver"),
        ("Karaoke song: ballad or banger?", "Ballad", "Banger"),
        ("Board game winner: bragging rights or humble nod?", "Brag", "Humble"),
        ("Losing gracefully or winning dramatically?", "Gracefully", "Dramatically"),
        ("Truth or dare?", "Truth", "Dare"),
        ("Would you rather know it all or have seen it all?", "Know it all", "Seen it all"),
    ],

    "general": [
        ("Choose one: kind or funny?", "Kind", "Funny"),
        ("Choose one: brave or lucky?", "Brave", "Lucky"),
        ("Choose one: wise or wealthy?", "Wise", "Wealthy"),
        ("Choose one: tall or short?", "Tall", "Short"),
        ("Choose one: fast or strong?", "Fast", "Strong"),
        ("Choose one: loud or quiet?", "Loud", "Quiet"),
        ("Choose one: early or late?", "Early", "Late"),
        ("Choose one: sweet or savory?", "Sweet", "Savory"),
        ("Choose one: hot or cold?", "Hot", "Cold"),
        ("Choose one: wet or dry?", "Wet", "Dry"),
        ("Choose one: new or old?", "New", "Old"),
        ("Choose one: big or small?", "Big", "Small"),
        ("Choose one: simple or complex?", "Simple", "Complex"),
        ("Choose one: safe or risky?", "Safe", "Risky"),
        ("Choose one: soft or firm?", "Soft", "Firm"),
        ("Choose one: bright or dark?", "Bright", "Dark"),
        ("Choose one: quiet mountains or busy city?", "Mountains", "City"),
        ("Choose one: book or movie?", "Book", "Movie"),
        ("Choose one: cats or dogs forever?", "Cats", "Dogs"),
        ("Choose one: summer or winter?", "Summer", "Winter"),
        ("Choose one: night in or night out?", "In", "Out"),
        ("Choose one: tea or coffee forever?", "Tea", "Coffee"),
        ("Choose one: texting or talking?", "Texting", "Talking"),
        ("Choose one: saving or spending?", "Saving", "Spending"),
        ("Choose one: planning or spontaneity?", "Planning", "Spontaneity"),
        ("Choose one: working or resting?", "Working", "Resting"),
        ("Choose one: laughing or thinking?", "Laughing", "Thinking"),
        ("Choose one: giving or receiving gifts?", "Giving", "Receiving"),
        ("Choose one: asking or answering?", "Asking", "Answering"),
        ("Choose one: starting or finishing?", "Starting", "Finishing"),
        ("Choose one: winning or participating?", "Winning", "Participating"),
        ("Choose one: leading or supporting?", "Leading", "Supporting"),
        ("Choose one: tradition or change?", "Tradition", "Change"),
        ("Choose one: privacy or transparency?", "Privacy", "Transparency"),
        ("Choose one: speed or accuracy?", "Speed", "Accuracy"),
        ("Choose one: form or function?", "Form", "Function"),
        ("Choose one: style or comfort?", "Style", "Comfort"),
        ("Choose one: quality or convenience?", "Quality", "Convenience"),
        ("Choose one: fame or anonymity?", "Fame", "Anonymity"),
        ("Choose one: silence or music?", "Silence", "Music"),
    ],
}
