"""Seed questions: question_seed_fun.
Format: {category_id: [(prompt, option1, option2), ...]}
"""

SEED = {
    "entertainment": [
        ('Marvel or DC?', 'Marvel', 'DC'),
        ('Star Wars or Star Trek?', 'Star Wars', 'Star Trek'),
        ('Harry Potter or Lord of the Rings?', 'Harry Potter', 'LOTR'),
        ('Batman or Spider-Man?', 'Batman', 'Spider-Man'),
        ('Superman or Wonder Woman?', 'Superman', 'Wonder Woman'),
        ('Breaking Bad or The Sopranos?', 'Breaking Bad', 'The Sopranos'),
        ('Friends or How I Met Your Mother?', 'Friends', 'HIMYM'),
        ('The Office or Parks and Recreation?', 'The Office', 'Parks and Rec'),
        ('Stranger Things or Dark?', 'Stranger Things', 'Dark'),
        ('Game of Thrones or The Witcher?', 'GoT', 'The Witcher'),
        ('Squid Game or Alice in Borderland?', 'Squid Game', 'Alice'),
        ('Money Heist or Peaky Blinders?', 'Money Heist', 'Peaky Blinders'),
        ('The Crown or Downton Abbey?', 'The Crown', 'Downton'),
        ('Sherlock or Lupin?', 'Sherlock', 'Lupin'),
        ('K-dramas or Turkish dramas?', 'K-dramas', 'Turkish dramas'),
        ('Anime or manga?', 'Anime', 'Manga'),
        ('Naruto or One Piece?', 'Naruto', 'One Piece'),
        ('Dragon Ball or Pokémon?', 'Dragon Ball', 'Pokémon'),
        ('Studio Ghibli or Pixar?', 'Ghibli', 'Pixar'),
        ('Toy Story or Shrek?', 'Toy Story', 'Shrek'),
        ('Frozen or Moana?', 'Frozen', 'Moana'),
        ('The Lion King or Aladdin?', 'Lion King', 'Aladdin'),
        ('Disney classics or Disney live-action?', 'Classics', 'Live-action'),
        ('Musicals or animated films?', 'Musicals', 'Animated'),
        ('La La Land or The Greatest Showman?', 'La La Land', 'Greatest Showman'),
        ('Horror films or psychological thrillers?', 'Horror', 'Thrillers'),
        ('The Conjuring or Insidious?', 'Conjuring', 'Insidious'),
        ('Zombie movies or vampire movies?', 'Zombies', 'Vampires'),
        ('Aliens or ghosts?', 'Aliens', 'Ghosts'),
        ('Found footage or traditional horror?', 'Found footage', 'Traditional'),
        ('Action franchises: Fast or Mission Impossible?', 'Fast', 'Mission Impossible'),
        ('James Bond or Jason Bourne?', 'Bond', 'Bourne'),
        ('John Wick or Taken?', 'John Wick', 'Taken'),
        ('Quentin Tarantino or Christopher Nolan?', 'Tarantino', 'Nolan'),
        ('Spielberg or Scorsese?', 'Spielberg', 'Scorsese'),
        ('Inception or Interstellar?', 'Inception', 'Interstellar'),
        ('The Matrix or Blade Runner?', 'Matrix', 'Blade Runner'),
        ('Dune or Arrival?', 'Dune', 'Arrival'),
        ('Oppenheimer or Barbie?', 'Oppenheimer', 'Barbie'),
        ('Rom-coms or tearjerkers?', 'Rom-coms', 'Tearjerkers'),
        ('The Notebook or La La Land ending?', 'The Notebook', 'La La Land'),
        ('Titanic or The Titanic documentary?', 'Titanic', 'Documentary'),
        ('Sitcoms or dramedies?', 'Sitcoms', 'Dramedies'),
        ('Reality dating shows or reality survival shows?', 'Dating', 'Survival'),
        ('Love Island or Bachelor Nation?', 'Love Island', 'Bachelor'),
        ('Cooking competitions or baking competitions?', 'Cooking', 'Baking'),
        ('The Great British Bake Off or MasterChef?', 'Bake Off', 'MasterChef'),
        ("RuPaul's Drag Race or America's Got Talent?", 'Drag Race', 'AGT'),
        ('Survivor or The Amazing Race?', 'Survivor', 'Amazing Race'),
        ('Talk shows or late-night comedy?', 'Talk shows', 'Late-night'),
        ('Podcasts: interview or storytelling?', 'Interview', 'Storytelling'),
        ('True crime podcasts or comedy podcasts?', 'True crime', 'Comedy'),
        ('Serial or This American Life?', 'Serial', 'TAL'),
        ('Audiobooks narrated by authors or actors?', 'Authors', 'Actors'),
        ('Music: oldies or current hits?', 'Oldies', 'Current'),
        ('Vinyl records or digital streaming?', 'Vinyl', 'Streaming'),
        ('Cassettes or CDs?', 'Cassettes', 'CDs'),
        ('Pop or rock?', 'Pop', 'Rock'),
        ('Hip-hop or R&B?', 'Hip-hop', 'R&B'),
        ('Country or folk?', 'Country', 'Folk'),
        ('Jazz or blues?', 'Jazz', 'Blues'),
        ('Classical or lo-fi?', 'Classical', 'Lo-fi'),
        ('EDM or house?', 'EDM', 'House'),
        ('Reggaeton or Afrobeat?', 'Reggaeton', 'Afrobeat'),
        ('K-pop or J-pop?', 'K-pop', 'J-pop'),
        ('Beyoncé or Rihanna?', 'Beyoncé', 'Rihanna'),
        ('Taylor Swift or Adele?', 'Taylor Swift', 'Adele'),
        ('Drake or Kendrick?', 'Drake', 'Kendrick'),
        ('The Beatles or The Rolling Stones?', 'Beatles', 'Stones'),
        ('Queen or ABBA?', 'Queen', 'ABBA'),
        ('Michael Jackson or Prince?', 'MJ', 'Prince'),
        ('Elvis or Sinatra?', 'Elvis', 'Sinatra'),
        ('Nirvana or Pearl Jam?', 'Nirvana', 'Pearl Jam'),
        ('Concerts small venue or stadium?', 'Small venue', 'Stadium'),
        ('Music festivals one-day or full weekend?', 'One day', 'Full weekend'),
        ('Front row at a concert or backstage pass?', 'Front row', 'Backstage'),
        ('Karaoke classic rock or karaoke pop?', 'Rock', 'Pop'),
        ("Dance like nobody's watching or watch everybody dance?", 'Dance', 'Watch'),
        ('Music videos or lyric videos?', 'Music videos', 'Lyric videos'),
        ('Albums front to back or shuffle everything?', 'Front to back', 'Shuffle'),
        ('Radio or personal playlist?', 'Radio', 'Playlist'),
        ('Video games: story mode or multiplayer?', 'Story mode', 'Multiplayer'),
        ('Mario or Zelda?', 'Mario', 'Zelda'),
        ('PlayStation or Xbox?', 'PlayStation', 'Xbox'),
        ('Nintendo Switch or Steam Deck?', 'Switch', 'Steam Deck'),
        ('Minecraft or Roblox?', 'Minecraft', 'Roblox'),
        ('Fortnite or Call of Duty?', 'Fortnite', 'CoD'),
        ('FIFA or NBA 2K?', 'FIFA', 'NBA 2K'),
        ('Chess or checkers?', 'Chess', 'Checkers'),
        ('Monopoly or Risk?', 'Monopoly', 'Risk'),
        ('Scrabble or Wordle?', 'Scrabble', 'Wordle'),
        ('Catan or Ticket to Ride?', 'Catan', 'Ticket to Ride'),
        ('Cards Against Humanity or Charades?', 'CAH', 'Charades'),
        ('Poker night or blackjack night?', 'Poker', 'Blackjack'),
        ('Trivia: general knowledge or pop culture?', 'General', 'Pop culture'),
        ('Escape rooms: horror themed or mystery themed?', 'Horror', 'Mystery'),
        ('Improv show or stand-up show?', 'Improv', 'Stand-up'),
        ('Circus or magic show?', 'Circus', 'Magic'),
        ('Drive-in revival or IMAX experience?', 'Drive-in', 'IMAX'),
        ('Film festivals or premiere nights?', 'Festivals', 'Premieres'),
        ('Watch the trailer or go in blind?', 'Trailer', 'Blind'),
        ('Read the book first or watch first?', 'Book first', 'Watch first'),
        ('Subtitles for foreign films or dubs?', 'Subtitles', 'Dubs'),
        ('Series finale: satisfying or controversial?', 'Satisfying', 'Controversial'),
        ('Binge now or savor weekly?', 'Binge', 'Weekly'),
        ('Spoiler alerts respected or spoilers welcome?', 'Respected', 'Welcome'),
        ('Watch parties or solo viewing?', 'Watch parties', 'Solo'),
        ('Awards shows watched live or recapped after?', 'Live', 'Recap'),
        ('Oscars best picture: popular or artsy?', 'Popular', 'Artsy'),
        ('Reboots welcome or leave the classics?', 'Reboots', 'Leave classics'),
        ('Streaming password shared or private?', 'Shared', 'Private'),
        ('Cancel subscriptions often or keep them all?', 'Cancel often', 'Keep all'),
        ('One more episode or sleep?', 'One more', 'Sleep'),
    ],
    "technology": [
        ('Face ID or fingerprint?', 'Face ID', 'Fingerprint'),
        ('Phone notifications batched or instant?', 'Batched', 'Instant'),
        ('Dark mode or light mode forever?', 'Dark', 'Light'),
        ('One monitor or dual monitors?', 'One', 'Dual'),
        ('Mechanical keyboard or membrane?', 'Mechanical', 'Membrane'),
        ('Mouse or trackpad?', 'Mouse', 'Trackpad'),
        ('Laptop stickers or clean lid?', 'Stickers', 'Clean'),
        ('Phone case rugged or minimal?', 'Rugged', 'Minimal'),
        ('Screen protector or naked screen?', 'Protector', 'Naked'),
        ('Wireless charging or fast cable?', 'Wireless', 'Fast cable'),
        ('Battery saver always or full brightness?', 'Battery saver', 'Full bright'),
        ('Phone upgrade yearly or ride it out?', 'Yearly', 'Ride it out'),
        ('Android customization or iPhone simplicity?', 'Customization', 'Simplicity'),
        ('Google ecosystem or Apple ecosystem?', 'Google', 'Apple'),
        ('Smartwatch or fitness band?', 'Smartwatch', 'Fitness band'),
        ('Smart speaker in every room or none?', 'Every room', 'None'),
        ('Smart doorbell or smart lock?', 'Doorbell', 'Lock'),
        ('Smart lights or smart thermostat first?', 'Lights', 'Thermostat'),
        ('Robot vacuum or robot mop?', 'Vacuum', 'Mop'),
        ('TV streaming stick or smart TV apps?', 'Stick', 'Smart TV'),
        ('Noise cancelling or transparency mode?', 'Noise cancelling', 'Transparency'),
        ('Earbuds or over-ear headphones?', 'Earbuds', 'Over-ear'),
        ('Bone conduction or traditional headphones?', 'Bone conduction', 'Traditional'),
        ('Voice typing or thumb typing?', 'Voice', 'Thumb'),
        ('GIF replies or emoji replies?', 'GIFs', 'Emoji'),
        ('Emoji reactions or text replies?', 'Reactions', 'Text'),
        ('Emoji: classics or new designs?', 'Classics', 'New designs'),
        ('Video messages or voice notes?', 'Video', 'Voice notes'),
        ('Group chats active or muted?', 'Active', 'Muted'),
        ('Zoom happy hours or in-person?', 'Zoom', 'In person'),
        ('Cloud backup or external drive?', 'Cloud', 'External drive'),
        ('NAS at home or cloud storage?', 'NAS', 'Cloud'),
        ('Password manager or memory?', 'Manager', 'Memory'),
        ('Two-factor everywhere or convenience first?', 'Everywhere', 'Convenience'),
        ('Password resets often or one forever?', 'Often', 'One forever'),
        ('VPN always on or public wifi courage?', 'VPN', 'Courage'),
        ('Ad blocker or support the sites?', 'Ad block', 'Support sites'),
        ('Cookies accepted or rejected?', 'Accept all', 'Reject'),
        ('Incognito mode regular or rare?', 'Regular', 'Rare'),
        ('Social media cleanse quarterly or never?', 'Quarterly', 'Never'),
        ('Doom scrolling at night or disciplined?', 'Doom scroll', 'Disciplined'),
        ('AI assistant for questions or search engine?', 'AI assistant', 'Search'),
        ('AI writing help or your own words?', 'AI help', 'Own words'),
        ('AI art impressive or unsettling?', 'Impressive', 'Unsettling'),
        ('Self-driving cars exciting or scary?', 'Exciting', 'Scary'),
        ('Drone photography or ground photography?', 'Drone', 'Ground'),
        ('VR headsets or AR glasses?', 'VR', 'AR'),
        ('Metaverse curiosity or metaverse skepticism?', 'Curiosity', 'Skepticism'),
        ('Crypto believer or crypto skeptic?', 'Believer', 'Skeptic'),
        ('NFTs art or NFTs scam?', 'Art', 'Scam'),
        ('Terminal commands or GUI clicks?', 'Terminal', 'GUI'),
        ('Linux or Windows daily?', 'Linux', 'Windows'),
        ('Open source loyalty or best tool wins?', 'Open source', 'Best tool'),
        ('Coding as hobby or coding as career?', 'Hobby', 'Career'),
        ('Build your PC or buy prebuilt?', 'Build', 'Prebuilt'),
        ('Cable management obsessed or spaghetti desk?', 'Obsessed', 'Spaghetti'),
        ('Standing desk converter or full desk?', 'Converter', 'Full desk'),
        ('Ergonomic chair or gaming chair?', 'Ergonomic', 'Gaming'),
        ('Desk plants or desk gadgets?', 'Plants', 'Gadgets'),
        ('Digital minimalism or app abundance?', 'Minimalism', 'Abundance'),
        ('Folder organization or search everything?', 'Folders', 'Search'),
        ('Desktop icons everywhere or clean desktop?', 'Everywhere', 'Clean'),
        ('Email folders or inbox search?', 'Folders', 'Search'),
        ('Tablet as laptop replacement or companion?', 'Replacement', 'Companion'),
        ('E-reader or tablet for reading?', 'E-reader', 'Tablet'),
        ('Smart home privacy concerns or convenience wins?', 'Privacy', 'Convenience'),
        ('Tech early adopter or late majority?', 'Early', 'Late'),
    ],
    "sports": [
        ('Football or basketball to watch?', 'Football', 'Basketball'),
        ('Tennis or golf to play?', 'Tennis', 'Golf'),
        ('Individual sports or team sports?', 'Individual', 'Team'),
        ('Summer Olympics or Winter Olympics?', 'Summer', 'Winter'),
        ('World Cup or Champions League?', 'World Cup', 'Champions League'),
        ('Premier League or La Liga?', 'Premier League', 'La Liga'),
        ('Messi or Ronaldo?', 'Messi', 'Ronaldo'),
        ('LeBron or Jordan?', 'LeBron', 'Jordan'),
        ('Kobe or Shaq?', 'Kobe', 'Shaq'),
        ('Federer or Nadal?', 'Federer', 'Nadal'),
        ('Djokovic or the field?', 'Djokovic', 'The field'),
        ('Serena or Venus?', 'Serena', 'Venus'),
        ('F1 or MotoGP?', 'F1', 'MotoGP'),
        ('Hamilton or Verstappen?', 'Hamilton', 'Verstappen'),
        ('Le Mans or Monaco GP?', 'Le Mans', 'Monaco'),
        ('Rally racing or circuit racing?', 'Rally', 'Circuit'),
        ('Boxing or MMA?', 'Boxing', 'MMA'),
        ('UFC or bellator?', 'UFC', 'Bellator'),
        ('Cricket or baseball?', 'Cricket', 'Baseball'),
        ('T20 or test cricket?', 'T20', 'Test'),
        ('Rugby or American football?', 'Rugby', 'American football'),
        ('Swimming or athletics?', 'Swimming', 'Athletics'),
        ('Sprinting or marathon?', 'Sprinting', 'Marathon'),
        ('Triathlon or ultramarathon?', 'Triathlon', 'Ultra'),
        ('Cycling road or mountain?', 'Road', 'Mountain'),
        ('Skateboarding or BMX?', 'Skate', 'BMX'),
        ('Snowboarding or skiing?', 'Snowboarding', 'Skiing'),
        ('Surfing or windsurfing?', 'Surfing', 'Windsurfing'),
        ('Rock climbing indoor or outdoor?', 'Indoor', 'Outdoor'),
        ('Bouldering or top rope?', 'Bouldering', 'Top rope'),
        ('Parkour or freerunning?', 'Parkour', 'Freerunning'),
        ('Martial arts: karate or judo?', 'Karate', 'Judo'),
        ('Taekwondo or kickboxing?', 'Taekwondo', 'Kickboxing'),
        ('Yoga as sport or yoga as practice?', 'Sport', 'Practice'),
        ('Pilates reformer or mat?', 'Reformer', 'Mat'),
        ('CrossFit or traditional gym?', 'CrossFit', 'Traditional'),
        ('HIIT or steady state cardio?', 'HIIT', 'Steady state'),
        ('Free weights or machines?', 'Free weights', 'Machines'),
        ('Deadlift or squat PR?', 'Deadlift', 'Squat'),
        ('Push-ups or pull-ups?', 'Push-ups', 'Pull-ups'),
        ('Plank challenge or burpee challenge?', 'Plank', 'Burpees'),
        ('Treadmill or elliptical?', 'Treadmill', 'Elliptical'),
        ('Spin class or solo ride?', 'Spin class', 'Solo'),
        ('Run with music or run with podcasts?', 'Music', 'Podcasts'),
        ('Morning run or evening run?', 'Morning', 'Evening'),
        ('Run outdoors or run indoors?', 'Outdoors', 'Indoors'),
        ('5K speed or marathon endurance?', '5K speed', 'Marathon'),
        ('Race for the medal or race for the vibe?', 'Medal', 'Vibe'),
        ('Fantasy sports league or no thanks?', 'Yes', 'No thanks'),
        ('Sports radio or sports podcasts?', 'Radio', 'Podcasts'),
        ('Watch at the stadium or at the bar?', 'Stadium', 'Bar'),
        ('Season tickets or pick and choose?', 'Season tickets', 'Pick and choose'),
        ('Jersey wearing or subtle support?', 'Jersey', 'Subtle'),
        ('Play in a rec league or watch only?', 'Rec league', 'Watch only'),
        ('Ping pong or foosball?', 'Ping pong', 'Foosball'),
        ('Darts or pool?', 'Darts', 'Pool'),
        ('Bowling league or casual bowling?', 'League', 'Casual'),
        ('Air hockey or arcade basketball?', 'Air hockey', 'Arcade hoops'),
        ('Trampoline parks or obstacle courses?', 'Trampoline', 'Obstacles'),
        ('Paintball or airsoft?', 'Paintball', 'Airsoft'),
        ('Laser tag or escape rooms?', 'Laser tag', 'Escape rooms'),
        ('Go-karting indoor or outdoor?', 'Indoor', 'Outdoor'),
        ('Betting on the game or friendly wagers?', 'Betting', 'Friendly'),
        ('Sports documentaries or highlight reels?', 'Documentaries', 'Highlights'),
        ('Rivalry games or finals games?', 'Rivalries', 'Finals'),
        ('Underdog story or dynasty story?', 'Underdog', 'Dynasty'),
        ('Overtime thrillers or blowouts?', 'Overtime', 'Blowouts'),
        ('Stats and analytics or eye test?', 'Analytics', 'Eye test'),
        ('Live score alerts or check later?', 'Alerts', 'Later'),
    ],
    "fashion": [
        ('Sneakers with everything or boots with everything?', 'Sneakers', 'Boots'),
        ('White sneakers or colorful sneakers?', 'White', 'Colorful'),
        ('High tops or low tops?', 'High tops', 'Low tops'),
        ('Loafers or brogues?', 'Loafers', 'Brogues'),
        ('Sandals summer or slides summer?', 'Sandals', 'Slides'),
        ('Flip-flops vacation or barefoot vacation?', 'Flip-flops', 'Barefoot'),
        ('Heels or flats for events?', 'Heels', 'Flats'),
        ('Stilettos or block heels?', 'Stilettos', 'Block heels'),
        ('Ankle boots or knee-high boots?', 'Ankle', 'Knee-high'),
        ('Leather jacket or denim jacket?', 'Leather', 'Denim'),
        ('Blazer or cardigan?', 'Blazer', 'Cardigan'),
        ('Hoodies or sweaters?', 'Hoodies', 'Sweaters'),
        ('Turtlenecks or V-necks?', 'Turtlenecks', 'V-necks'),
        ('Crewnecks or collared shirts?', 'Crewnecks', 'Collars'),
        ('Oversized fit or tailored fit?', 'Oversized', 'Tailored'),
        ('Slim fit or straight fit?', 'Slim', 'Straight'),
        ('Athleisure all day or dressed up all day?', 'Athleisure', 'Dressed up'),
        ('Monochrome outfits or colorful outfits?', 'Monochrome', 'Colorful'),
        ('Neutrals wardrobe or rainbow wardrobe?', 'Neutrals', 'Rainbow'),
        ('Pastels or jewel tones?', 'Pastels', 'Jewel tones'),
        ('Earth tones or neon pops?', 'Earth tones', 'Neon'),
        ('Animal print or metallics?', 'Animal print', 'Metallics'),
        ('Stripes or polka dots?', 'Stripes', 'Polka dots'),
        ('Plaid or floral?', 'Plaid', 'Floral'),
        ('Camouflage or tie-dye?', 'Camo', 'Tie-dye'),
        ('Black tie events or smart casual events?', 'Black tie', 'Smart casual'),
        ('Suit and tie or suit no tie?', 'Tie', 'No tie'),
        ('Dress or pants for formal events?', 'Dress', 'Pants'),
        ('Maxi dresses or mini dresses?', 'Maxi', 'Mini'),
        ('Midi skirts or pleated skirts?', 'Midi', 'Pleated'),
        ('Wide-leg pants or skinny pants?', 'Wide-leg', 'Skinny'),
        ('Cargo pants or joggers?', 'Cargo', 'Joggers'),
        ('Jeans: light wash or dark wash?', 'Light wash', 'Dark wash'),
        ('Distressed denim or clean denim?', 'Distressed', 'Clean'),
        ('Raw denim or stretch denim?', 'Raw', 'Stretch'),
        ('Shorts summer or pants summer?', 'Shorts', 'Pants'),
        ('Swim trunks or swim briefs?', 'Trunks', 'Briefs'),
        ('One-piece swimsuit or two-piece?', 'One-piece', 'Two-piece'),
        ('Accessories: gold or silver?', 'Gold', 'Silver'),
        ('Layered necklaces or statement necklace?', 'Layered', 'Statement'),
        ('Hoops or studs?', 'Hoops', 'Studs'),
        ('Watches: analog or digital?', 'Analog', 'Digital'),
        ('Smartwatch dressed up or hidden?', 'Dressed up', 'Hidden'),
        ('Bracelets or rings?', 'Bracelets', 'Rings'),
        ('Stacked rings or single ring?', 'Stacked', 'Single'),
        ('Hats: baseball cap or beanie?', 'Baseball cap', 'Beanie'),
        ('Bucket hats or fedoras?', 'Bucket', 'Fedora'),
        ('Sun hats or visors?', 'Sun hat', 'Visor'),
        ('Scarves or shawls?', 'Scarves', 'Shawls'),
        ('Sunglasses: aviators or wayfarers?', 'Aviators', 'Wayfarers'),
        ('Round frames or rectangular frames?', 'Round', 'Rectangular'),
        ('Clear lenses or tinted lenses?', 'Clear', 'Tinted'),
        ('Glasses or contacts?', 'Glasses', 'Contacts'),
        ('Belts or beltless?', 'Belts', 'Beltless'),
        ('Bags: crossbody or backpack?', 'Crossbody', 'Backpack'),
        ('Tote bags or shoulder bags?', 'Tote', 'Shoulder'),
        ('Clutch for nights out or mini backpack?', 'Clutch', 'Mini backpack'),
        ('Wallet slim or wallet chunky?', 'Slim', 'Chunky'),
        ('Shopping: sale racks or full price?', 'Sale racks', 'Full price'),
        ('Seasonal wardrobe refresh or capsule wardrobe?', 'Refresh', 'Capsule'),
    ],
    "nature": [
        ('Ocean waves or mountain echoes?', 'Waves', 'Echoes'),
        ('Forest walk or meadow stroll?', 'Forest', 'Meadow'),
        ('Waterfalls or hot springs?', 'Waterfalls', 'Hot springs'),
        ('Caves or canyons?', 'Caves', 'Canyons'),
        ('Desert dunes or red rock cliffs?', 'Dunes', 'Red rocks'),
        ('Arctic tundra or tropical jungle?', 'Arctic', 'Jungle'),
        ('Coral reefs or kelp forests?', 'Coral', 'Kelp'),
        ('Northern lights or midnight sun?', 'Aurora', 'Midnight sun'),
        ('Thunderstorms or snowstorms?', 'Thunder', 'Snow'),
        ('Summer rain or winter frost?', 'Summer rain', 'Winter frost'),
        ('Autumn leaves or spring blossoms?', 'Autumn', 'Spring'),
        ('Cherry blossoms or lavender fields?', 'Cherry', 'Lavender'),
        ('Sunflower fields or poppy fields?', 'Sunflowers', 'Poppies'),
        ('Wildflower meadows or manicured gardens?', 'Wildflowers', 'Gardens'),
        ('Bamboo forest or pine forest?', 'Bamboo', 'Pine'),
        ('Oak trees or willow trees?', 'Oak', 'Willow'),
        ('Cacti or succulents?', 'Cacti', 'Succulents'),
        ('Bonsai or terrariums?', 'Bonsai', 'Terrarium'),
        ('Mushroom foraging or berry picking?', 'Mushrooms', 'Berries'),
        ('Birdwatching dawn or birdwatching dusk?', 'Dawn', 'Dusk'),
        ('Owls or eagles?', 'Owls', 'Eagles'),
        ('Penguins or puffins?', 'Penguins', 'Puffins'),
        ('Flamingos or peacocks?', 'Flamingos', 'Peacocks'),
        ('Parrots or cockatoos?', 'Parrots', 'Cockatoos'),
        ('Hummingbirds or butterflies?', 'Hummingbirds', 'Butterflies'),
        ('Fireflies or glowworms?', 'Fireflies', 'Glowworms'),
        ('Ladybugs or dragonflies?', 'Ladybugs', 'Dragonflies'),
        ('Bees or ants as neighbors?', 'Bees', 'Ants'),
        ('Horses or deer?', 'Horses', 'Deer'),
        ('Foxes or wolves?', 'Foxes', 'Wolves'),
        ('Bears or moose?', 'Bears', 'Moose'),
        ('Rabbits or squirrels?', 'Rabbits', 'Squirrels'),
        ('Hedgehogs or otters?', 'Hedgehogs', 'Otters'),
        ('Pandas or koalas?', 'Pandas', 'Koalas'),
        ('Sloths or lemurs?', 'Sloths', 'Lemurs'),
        ('Elephants or giraffes?', 'Elephants', 'Giraffes'),
        ('Lions or tigers?', 'Lions', 'Tigers'),
        ('Leopards or cheetahs?', 'Leopards', 'Cheetahs'),
        ('Whale watching or dolphin watching?', 'Whales', 'Dolphins'),
        ('Sea turtles or seals?', 'Turtles', 'Seals'),
        ('Octopuses or seahorses?', 'Octopuses', 'Seahorses'),
        ('Jellyfish or starfish?', 'Jellyfish', 'Starfish'),
        ('Sharks or rays?', 'Sharks', 'Rays'),
        ('Coral or pearls?', 'Coral', 'Pearls'),
        ('Seashell collecting or rock collecting?', 'Shells', 'Rocks'),
        ('Skipping stones or building sandcastles?', 'Skipping stones', 'Sandcastles'),
        ('Stargazing or moon watching?', 'Stars', 'Moon'),
        ('Full moon or crescent moon?', 'Full', 'Crescent'),
        ('Meteor showers or eclipses?', 'Meteors', 'Eclipses'),
        ('Sunrise hikes or sunset picnics?', 'Sunrise hikes', 'Sunset picnics'),
        ('Camping in forests or camping by lakes?', 'Forests', 'Lakes'),
        ('Hammock between trees or tent under stars?', 'Hammock', 'Tent'),
        ('Fishing or foraging?', 'Fishing', 'Foraging'),
        ('Kayaking rivers or kayaking lakes?', 'Rivers', 'Lakes'),
        ('Snorkeling shallow reefs or deep dives?', 'Shallow', 'Deep'),
        ('Surfing morning or swimming midnight?', 'Morning surf', 'Midnight swim'),
        ('Gardening flowers or vegetables?', 'Flowers', 'Vegetables'),
        ('Composting or rainwater collecting?', 'Compost', 'Rainwater'),
        ('National parks or nature reserves?', 'National parks', 'Reserves'),
        ('Zoos or sanctuaries?', 'Zoos', 'Sanctuaries'),
        ('Pets: adopted or rescued?', 'Adopted', 'Rescued'),
        ('Dogs off-leash beaches or dogs on trails?', 'Beaches', 'Trails'),
        ('Cats indoor or cats outdoor?', 'Indoor', 'Outdoor'),
    ],
    "work": [
        ('Email first thing or email after lunch?', 'First thing', 'After lunch'),
        ('Inbox zero or inbox archive-all?', 'Zero', 'Archive all'),
        ('Meetings in the morning or afternoons?', 'Morning', 'Afternoon'),
        ('Camera on or camera off?', 'On', 'Off'),
        ('Video calls or audio calls?', 'Video', 'Audio'),
        ('Stand-up meetings or async updates?', 'Stand-up', 'Async'),
        ('Brainstorms in groups or solo first?', 'Group', 'Solo first'),
        ('Open office or remote forever?', 'Open office', 'Remote'),
        ('Hybrid week or fully onsite?', 'Hybrid', 'Onsite'),
        ('Home office or coworking space?', 'Home', 'Coworking'),
        ('Coffee shop working or library working?', 'Coffee shop', 'Library'),
        ('Commute by car or public transport?', 'Car', 'Public transport'),
        ('Commute podcast or commute silence?', 'Podcast', 'Silence'),
        ('Flexible hours or set schedule?', 'Flexible', 'Set'),
        ('Four-day week or five-day week?', 'Four-day', 'Five-day'),
        ('Early shifts or late shifts?', 'Early', 'Late'),
        ('Overtime for money or overtime never?', 'For money', 'Never'),
        ('Salary or equity?', 'Salary', 'Equity'),
        ('Bonus or raise?', 'Bonus', 'Raise'),
        ('Title bump or pay bump?', 'Title', 'Pay'),
        ('Big company or small startup?', 'Big company', 'Startup'),
        ('Corporate structure or flat hierarchy?', 'Corporate', 'Flat'),
        ('Known company or exciting unknown?', 'Known', 'Unknown'),
        ('Manager track or expert track?', 'Manager', 'Expert'),
        ('Lead the team or mentor quietly?', 'Lead', 'Mentor'),
        ('Delegate or do it yourself?', 'Delegate', 'DIY'),
        ('Perfection shipped late or good shipped now?', 'Perfect and late', 'Good now'),
        ('Deep work blocks or reactive flow?', 'Deep blocks', 'Reactive'),
        ('Music while working or silence?', 'Music', 'Silence'),
        ('Desk plants or desk photos?', 'Plants', 'Photos'),
        ('Sticky notes or digital boards?', 'Sticky notes', 'Digital boards'),
        ('To-do list apps or a simple notebook?', 'Apps', 'Notebook'),
        ('Time blocking or task batching?', 'Time blocking', 'Batching'),
        ('Pomodoro sprints or natural rhythm?', 'Pomodoro', 'Natural rhythm'),
        ('Monday planning or Sunday planning?', 'Monday', 'Sunday'),
        ('Friday wrap-ups or Friday coasting?', 'Wrap-up', 'Coast'),
        ('Workations or proper vacations?', 'Workations', 'Proper vacations'),
        ('Unplug on vacation or check in?', 'Unplug', 'Check in'),
        ('Sick day: rest or work from bed?', 'Rest', 'Work from bed'),
        ('Feedback direct or feedback sandwiched?', 'Direct', 'Sandwiched'),
        ('Performance reviews or continuous feedback?', 'Reviews', 'Continuous'),
        ('Public praise or private praise?', 'Public', 'Private'),
        ('Constructive criticism or compliments first?', 'Criticism', 'Compliments'),
        ('Networking events or one-on-ones?', 'Events', 'One-on-ones'),
        ('LinkedIn active or LinkedIn dormant?', 'Active', 'Dormant'),
        ('Business cards or QR codes?', 'Cards', 'QR codes'),
        ('Work friends or professional distance?', 'Friends', 'Distance'),
        ('Office gossip or office silence?', 'Gossip', 'Silence'),
        ('Office parties: attend or escape?', 'Attend', 'Escape'),
        ('Team lunches or solo lunches?', 'Team', 'Solo'),
        ('Lunch walks or lunch naps?', 'Walks', 'Naps'),
        ('Coffee machine chats or quick exits?', 'Chats', 'Exits'),
        ('Dress to impress or dress for comfort?', 'Impress', 'Comfort'),
        ('Casual Friday every day or dressed up daily?', 'Casual daily', 'Dressed up'),
        ('Learning budget or conference budget?', 'Learning', 'Conferences'),
        ('Certifications or experience?', 'Certifications', 'Experience'),
        ('Side projects allowed or focused role?', 'Side projects', 'Focused'),
        ('Job hopping or long tenure?', 'Hopping', 'Tenure'),
        ('Resign in person or resignation letter?', 'In person', 'Letter'),
        ('Interviews honest or interviews polished?', 'Honest', 'Polished'),
        ('Dream company or dream role?', 'Company', 'Role'),
        ('Passion project or paying the bills?', 'Passion', 'Bills'),
        ('Retire early or never retire?', 'Early', 'Never'),
    ],
    "silly-fun": [
        ('Karaoke: sincerity or sabotage?', 'Sincerity', 'Sabotage'),
        ("Dance like everyone's watching or like nobody is?", "Everyone's watching", 'Nobody is'),
        ("Your partner's worst dance move: mock it or learn it?", 'Mock it', 'Learn it'),
        ('Couple costume at parties: yes or absolutely not?', 'Yes', 'Absolutely not'),
        ('Matching outfits once a year or never speak of it?', 'Once a year', 'Never'),
        ('Being photographed: candid chaos or director and vision?', 'Candid', 'Directed'),
        ('Their laugh in a quiet room: mortifying or your favorite sound?', 'Mortifying', 'Favorite'),
        ('Brag about your partner constantly or never in public?', 'Constantly', 'Never'),
        ('Google your symptoms together or hide the search history?', 'Together', 'Hide it'),
        ('Win the board game or save the marriage?', 'Win', 'Save it'),
        ('Monopoly: house rules or by the book?', 'House rules', 'By the book'),
        ('Road trip: their playlist or the great skipping war?', 'Their playlist', 'Skipping war'),
        ('Directions: navigator with opinions or silent GPS trust?', 'Opinionated', 'Silent trust'),
        ("The group chat with your friends: they're in it or it's classified?", 'In it', 'Classified'),
        ('Roast each other in public or save it for the car?', 'In public', 'The car'),
        ('Inside jokes in front of others: fair game or rude?', 'Fair game', 'Rude'),
        ('Being carded at 40: flattering or suspicious?', 'Flattering', 'Suspicious'),
        ('The birthday: full production or quiet dinner?', 'Production', 'Quiet dinner'),
        ('Surprise parties: love or legal hazard?', 'Love', 'Hazard'),
        ('Happy birthday on social media or said to your face?', 'Social media', 'To my face'),
        ('Small talk at parties: art form or hostage situation?', 'Art form', 'Hostage'),
        ('The office party: open bar or open bar-ely attend?', 'Open bar', 'Barely attend'),
        ('Reply-all incidents: forgive or screenshot forever?', 'Forgive', 'Screenshot'),
        ('A typo in the important email: laugh or spiral?', 'Laugh', 'Spiral'),
        ('Voice memos or voice notes of doom (calls)?', 'Voice memos', 'Actual calls'),
        ('Read receipts: honesty or aggression?', 'Honesty', 'Aggression'),
        ('The double text: confidence or chaos?', 'Confidence', 'Chaos'),
        ("Replied 'you too' to 'enjoy your meal' — move on or think about it for years?", 'Move on', 'Years'),
        ('Weddings: cry at every one or hold the line?', 'Every one', 'Hold the line'),
        ('The dance floor at 11 p.m. or the good chair by 10?', 'Dance floor', 'Good chair'),
        ('Hotel breakfast included or sleep through it?', 'Included', 'Sleep'),
        ('Mini-bar prices: scandal or vacation law?', 'Scandal', 'Vacation law'),
        ('Talking to the pet in full sentences or seeking help?', 'Full sentences', 'Seek help'),
        ('The pet clearly prefers your partner: accept or campaign?', 'Accept', 'Campaign'),
        ('Midnight snack shame: hidden wrapper or proud confession?', 'Hidden', 'Proud'),
        ('Bathroom door policy: open marriage of conveniences or locked like a vault?', 'Open', 'Vault'),
        ('Farted in the first year: confessed or took it to the grave?', 'Confessed', 'To the grave'),
        ('Their shower concerts: attend or charge admission?', 'Attend', 'Charge admission'),
        ('Bedtime routine: synchronized or diplomatic', 'Synchronized', 'Diplomatic'),
        ("The last slice: split it or 'I thought you didn't want it'?", 'Split it', "It's mine"),
        ('Argue about the thermostat or the volume of the TV?', 'Thermostat', 'TV volume'),
        ('Pillow talk or pillow scroll?', 'Talk', 'Scroll'),
        ('The 2 a.m. idea: share it or it can wait till morning?', 'Share it', 'It waits'),
        ('Feet in winter: igloo or glacier?', 'Igloo', 'Glacier'),
        ('Their cold hands on your warm back: betrayal or affection?', 'Betrayal', 'Affection'),
        ('Wake them to kill the spider or negotiate alone?', 'Wake them', 'Negotiate'),
        ('The spider: relocate or consequence?', 'Relocate', 'Consequence'),
        ('Pineapple on pizza: crime or cuisine?', 'Crime', 'Cuisine'),
        ('The Oxford comma: defender or anarchist?', 'Defender', 'Anarchist'),
        ('Cilantro: delicious or soap?', 'Delicious', 'Soap'),
        ('The toilet paper roll: over or under?', 'Over', 'Under'),
        ('Bank holidays: productive or horizontal?', 'Productive', 'Horizontal'),
        ('Big wedding or big down payment?', 'Wedding', 'Down payment'),
        ('Airport arrivals: four hours early or a brisk jog?', 'Four hours', 'Brisk jog'),
        ('Middle seat on a long flight: aisle-sacrifice or window-claim?', 'Aisle-sacrifice', 'Window-claim'),
        ('Airplane small talk: pleasant or headphones immediately?', 'Pleasant', 'Headphones'),
        ('Museums: read every plaque or vibe and wander?', 'Every plaque', 'Vibe'),
        ('Send the food back or suffer nobly?', 'Send it back', 'Suffer'),
        ('Split the bill to the cent or round and move on?', 'To the cent', 'Round up'),
        ('A friend is 20 minutes late: order or wait?', 'Order', 'Wait'),
        ('Haggling: thrilling or mortifying?', 'Thrilling', 'Mortifying'),
        ("A stranger's playlist on shuffle or silence on the train?", 'Their playlist', 'Silence'),
        ('Comment sections: read or resist?', 'Read', 'Resist'),
        ('The unskippable intro: anthem or obstacle?', 'Anthem', 'Obstacle'),
        ('Group photos: everybody jumping or one honest attempt?', 'Jumping', 'One honest'),
        ("New Year's resolutions: made or broken by Jan 12?", 'Made', 'Broken by Jan 12'),
        ('Horoscopes: read for fun or live by them?', 'For fun', 'Live by them'),
        ('Astrology at dinner parties: playful or painful?', 'Playful', 'Painful'),
        ("The friend who's always 'five minutes away': tease or tolerate?", 'Tease', 'Tolerate'),
        ('Truth or dare, still at your age?', 'Truth', 'Dare'),
        ('Would you rather your partner see your search history or your camera roll?', 'Search history', 'Camera roll'),
        ('Your partner reads your group chats aloud or your teenage diary?', 'Group chats', 'Diary'),
        ('Superpower: read their mind or rewind your own day?', 'Read minds', 'Rewind'),
        ('Swap lives for a week: enlightening or terrifying?', 'Enlightening', 'Terrifying'),
        ('A documentary crew follows you for a week: hit or disaster?', 'Hit', 'Disaster'),
        ('Your autobiography: who writes the foreword?', 'My partner', 'My best friend'),
        ('Lose the ability to lie or to ever be late again?', 'Stop lying', 'Never late'),
        ('Perfect memory of every moment together or the ability to forget cringes?', 'Perfect memory', 'Forget cringes'),
        ('The robot uprising: negotiate for humanity or your household first?', 'Humanity', 'My household'),
        ('One text sent to the wrong person: your boss or your mother-in-law?', 'Boss', 'Mother-in-law'),
        ("Trapped in an elevator with your ex or your partner's ex?", 'My ex', 'Their ex'),
        ('Karaoke duet with your partner: ballad or banger?', 'Ballad', 'Banger'),
        ('Your partner picks your haircut for a month or your outfits for a week?', 'Haircut', 'Outfits'),
        ('The group trip: planner by default or payment-avoider supreme?', 'Planner', 'Avoider'),
        ('Airport gate changed at the last second: zen or rage?', 'Zen', 'Rage'),
        ('Someone mispronounces your name for years: correct or carry on?', 'Correct', 'Carry on'),
        ("Your partner's terrible playlist: endure or intervene?", 'Endure', 'Intervene'),
        ('The wrong name at the wrong moment: laugh or investigate?', 'Laugh', 'Investigate'),
        ("Finish this: 'we can't go to that restaurant since…'", 'Say it', 'Never say it'),
    ],
    "general": [
        ('Choose one: kind or funny?', 'Kind', 'Funny'),
        ('Choose one: brave or lucky?', 'Brave', 'Lucky'),
        ('Choose one: wise or wealthy?', 'Wise', 'Wealthy'),
        ('Choose one: tall or short?', 'Tall', 'Short'),
        ('Choose one: fast or strong?', 'Fast', 'Strong'),
        ('Choose one: loud or quiet?', 'Loud', 'Quiet'),
        ('Choose one: early or late?', 'Early', 'Late'),
        ('Choose one: sweet or savory?', 'Sweet', 'Savory'),
        ('Choose one: hot or cold?', 'Hot', 'Cold'),
        ('Choose one: wet or dry?', 'Wet', 'Dry'),
        ('Choose one: new or old?', 'New', 'Old'),
        ('Choose one: big or small?', 'Big', 'Small'),
        ('Choose one: simple or complex?', 'Simple', 'Complex'),
        ('Choose one: safe or risky?', 'Safe', 'Risky'),
        ('Choose one: soft or firm?', 'Soft', 'Firm'),
        ('Choose one: bright or dark?', 'Bright', 'Dark'),
        ('Choose one: quiet mountains or busy city?', 'Mountains', 'City'),
        ('Choose one: book or movie?', 'Book', 'Movie'),
        ('Choose one: cats or dogs forever?', 'Cats', 'Dogs'),
        ('Choose one: summer or winter?', 'Summer', 'Winter'),
        ('Choose one: night in or night out?', 'In', 'Out'),
        ('Choose one: tea or coffee forever?', 'Tea', 'Coffee'),
        ('Choose one: texting or talking?', 'Texting', 'Talking'),
        ('Choose one: saving or spending?', 'Saving', 'Spending'),
        ('Choose one: planning or spontaneity?', 'Planning', 'Spontaneity'),
        ('Choose one: working or resting?', 'Working', 'Resting'),
        ('Choose one: laughing or thinking?', 'Laughing', 'Thinking'),
        ('Choose one: giving or receiving gifts?', 'Giving', 'Receiving'),
        ('Choose one: asking or answering?', 'Asking', 'Answering'),
        ('Choose one: starting or finishing?', 'Starting', 'Finishing'),
        ('Choose one: winning or participating?', 'Winning', 'Participating'),
        ('Choose one: leading or supporting?', 'Leading', 'Supporting'),
        ('Choose one: tradition or change?', 'Tradition', 'Change'),
        ('Choose one: privacy or transparency?', 'Privacy', 'Transparency'),
        ('Choose one: speed or accuracy?', 'Speed', 'Accuracy'),
        ('Choose one: form or function?', 'Form', 'Function'),
        ('Choose one: style or comfort?', 'Style', 'Comfort'),
        ('Choose one: quality or convenience?', 'Quality', 'Convenience'),
        ('Choose one: fame or anonymity?', 'Fame', 'Anonymity'),
        ('Choose one: silence or music?', 'Silence', 'Music'),
    ],
}
