"""Seed questions: couples-focused categories.
Format: {category_id: [(prompt, option1, option2), ...]}
"""

SEED = {
    "couples": [
        ("Good morning text or good night text?", "Good morning text", "Good night text"),
        ("Hold hands or link arms?", "Hold hands", "Link arms"),
        ("Forehead kiss or cheek kiss?", "Forehead kiss", "Cheek kiss"),
        ("Love letters or little notes in pockets?", "Love letters", "Notes in pockets"),
        ("Surprise gifts or surprises you plan together?", "Surprise gifts", "Planned together"),
        ("Breakfast in bed or breakfast at the table?", "Breakfast in bed", "At the table"),
        ("Matching outfits for parties or matching pajamas?", "Matching outfits", "Matching pajamas"),
        ("Pet names or real names?", "Pet names", "Real names"),
        ("Apologize first or forgive first?", "Apologize first", "Forgive first"),
        ("Talk it out immediately or sleep on it?", "Talk immediately", "Sleep on it"),
        ("Anniversary trip or anniversary gift?", "Anniversary trip", "Anniversary gift"),
        ("Flowers or chocolates?", "Flowers", "Chocolates"),
        ("Handwritten card or store-bought card?", "Handwritten card", "Store-bought card"),
        ("Cook dinner together or order in together?", "Cook together", "Order in"),
        ("Fall asleep first or stay up watching them sleep?", "Fall asleep first", "Stay up"),
        ("Slow dance in the kitchen or dance-off in the living room?", "Slow dance", "Dance-off"),
        ("Movie cuddle on the couch or movie hand-hold at the cinema?", "Couch cuddle", "Cinema hand-hold"),
        ("Shared calendar or surprise each other?", "Shared calendar", "Surprise each other"),
        ("Split chores by preference or swap weekly?", "By preference", "Swap weekly"),
        ("One blanket or two blankets?", "One blanket", "Two blankets"),
        ("Thermostat warm or thermostat cool?", "Warm", "Cool"),
        ("Sleep with TV on or total silence?", "TV on", "Silence"),
        ("Morning person wakes the other or lets them sleep?", "Wake them", "Let them sleep"),
        ("Shared hobbies or separate hobbies?", "Shared hobbies", "Separate hobbies"),
        ("Couple photos everywhere or keep it private?", "Photos everywhere", "Keep it private"),
        ("Post about each other online or keep it offline?", "Post online", "Keep offline"),
        ("Text throughout the day or catch up at night?", "Text all day", "Catch up at night"),
        ("Goodbye kiss at the door or goodbye text later?", "Kiss at the door", "Text later"),
        ("Reunions at the airport or reunions at home?", "Airport", "Home"),
        ("Long-distance letters or long-distance video calls?", "Letters", "Video calls"),
        ("Save the date nights or spontaneous dates?", "Scheduled date nights", "Spontaneous dates"),
        ("Double dates or just-us dates?", "Double dates", "Just us"),
        ("Group vacation or couple vacation?", "Group vacation", "Couple vacation"),
        ("Meet each other's coworkers or keep work separate?", "Meet coworkers", "Keep separate"),
        ("Fight over text or fight in person?", "Over text", "In person"),
        ("Silent treatment or say it straight away?", "Silent treatment", "Say it straight"),
        ("Compliments in public or compliments in private?", "In public", "In private"),
        ("Tease each other in front of friends or never?", "Tease playfully", "Never tease"),
        ("Remember every date or celebrate the big ones?", "Every date", "Big ones only"),
        ("Roses or tulips?", "Roses", "Tulips"),
        ("Candlelit bath or candlelit dinner?", "Candlelit bath", "Candlelit dinner"),
        ("Playlist of our songs or one special song?", "Playlist", "One special song"),
        ("Dedicated song or first-dance song?", "Dedicated song", "First-dance song"),
        ("Recreate the first date or plan something new?", "Recreate first date", "Something new"),
        ("Photograph every moment or live in the moment?", "Photograph", "Live the moment"),
        ("Scrapbook or digital photo album?", "Scrapbook", "Digital album"),
        ("Gift receipts or keep the surprise?", "Gift receipts", "Keep the surprise"),
        ("Practical gifts or romantic gifts?", "Practical", "Romantic"),
        ("Expensive one gift or many small ones?", "One expensive gift", "Many small gifts"),
        ("Experience gifts or object gifts?", "Experiences", "Objects"),
        ("Hug from behind or hug face to face?", "From behind", "Face to face"),
        ("Long hugs or frequent quick hugs?", "Long hugs", "Frequent quick hugs"),
        ("Kiss on the first date or wait?", "First date", "Wait"),
        ("Say 'I love you' early or wait months?", "Say it early", "Wait months"),
        ("Define the relationship early or let it evolve?", "Define early", "Let it evolve"),
        ("Meet the parents early or later?", "Early", "Later"),
        ("Spend holidays with your family or theirs?", "Your family", "Their family"),
        ("Alternate holidays or host everyone?", "Alternate", "Host everyone"),
        ("In-laws visit often or rarely?", "Often", "Rarely"),
        ("Share passwords or keep some privacy?", "Share passwords", "Some privacy"),
        ("Share a bank account or keep separate?", "Shared account", "Separate"),
        ("Split bills 50/50 or by income?", "50/50", "By income"),
        ("One of you budgets or both?", "One budgets", "Both budget"),
        ("Splurge on dates or save for the future?", "Splurge on dates", "Save for future"),
        ("Financial secrets or full transparency?", "Full transparency", "Some privacy"),
        ("Morning coffee together or evening tea together?", "Morning coffee", "Evening tea"),
        ("Grocery shopping together or alone?", "Together", "Alone"),
        ("Cook to recipe or improvise?", "Recipe", "Improvise"),
        ("Who cooks, who cleans or share both?", "One cooks one cleans", "Share both"),
        ("Dinner at 6 or dinner at 9?", "Dinner at 6", "Dinner at 9"),
        ("Weekend brunch or weekend lie-in?", "Brunch", "Lie-in"),
        ("Lazy Sunday or adventure Sunday?", "Lazy Sunday", "Adventure Sunday"),
        ("Sleep in separate rooms when snoring or endure?", "Separate rooms", "Endure"),
        ("King bed or two pushed-together beds?", "King bed", "Pushed together"),
        ("Fan on at night or fan off?", "Fan on", "Fan off"),
        ("Blackout curtains or sunlight waking?", "Blackout curtains", "Sunlight"),
        ("Alarm snooze together or jump up?", "Snooze", "Jump up"),
        ("Get ready together or take turns?", "Together", "Take turns"),
        ("Share a closet or own closets?", "Share closet", "Own closets"),
        ("Toothbrush cup sharing or separate?", "Share cup", "Separate"),
        ("Towel sharing or own towels?", "Share towels", "Own towels"),
        ("Sing in the car together or silent rides?", "Sing together", "Silent rides"),
        ("Road trip navigator or driver?", "Navigator", "Driver"),
        ("Window seat for you or for them?", "For me", "For them"),
        ("Carry their bag or let them carry it?", "Carry it", "They carry it"),
        ("Open doors for them or they for you?", "I open doors", "They open doors"),
        ("Walk on the traffic side or hold any side?", "Traffic side", "Any side"),
        ("Order for each other or own orders?", "Order for each other", "Own orders"),
        ("Share dessert or own desserts?", "Share dessert", "Own desserts"),
        ("Steal their fries or defend your own?", "Steal fries", "Defend mine"),
        ("Spicy food dates or mild food dates?", "Spicy", "Mild"),
        ("Fancy restaurant once a month or casual every week?", "Fancy monthly", "Casual weekly"),
        ("Try new restaurants or loyal favorites?", "New restaurants", "Loyal favorites"),
        ("Bar dates or café dates?", "Bar", "Café"),
        ("Cooking class or dance class together?", "Cooking class", "Dance class"),
        ("Board game night or video game night?", "Board games", "Video games"),
        ("Puzzle together or read side by side?", "Puzzle", "Read side by side"),
        ("Karaoke duet or karaoke solo?", "Duet", "Solo"),
        ("Trivia teammates or trivia rivals?", "Teammates", "Rivals"),
        ("Workout together or separately?", "Together", "Separately"),
        ("Morning walks or evening walks?", "Morning walks", "Evening walks"),
        ("Stargazing or cloud watching together?", "Stargazing", "Cloud watching"),
        ("Picnic in the park or rooftop drinks?", "Picnic", "Rooftop drinks"),
        ("Watch the sunset or chase the sunrise?", "Sunset", "Sunrise"),
        ("Rainy day inside or dancing in the rain?", "Inside", "Dance in the rain"),
        ("Build a snowman or hot cocoa by the fire?", "Snowman", "Hot cocoa"),
        ("Beach day together or mountain hike together?", "Beach day", "Mountain hike"),
        ("Couple's massage or surprise spa day?", "Couple's massage", "Surprise spa day"),
        ("Photo booth strips or professional shoots?", "Photo booth", "Professional shoots"),
        ("Matching rings or matching bracelets?", "Rings", "Bracelets"),
        ("Keep old love letters or digitize them?", "Keep them", "Digitize"),
        ("Celebrate monthly anniversaries or just yearly?", "Monthly", "Yearly"),
        ("Rename anniversaries or traditional names?", "Fun names", "Traditional"),
        ("Gift on Valentine's Day or random Tuesday?", "Valentine's Day", "Random Tuesday"),
        ("Propose publicly or privately?", "Publicly", "Privately"),
        ("Big proposal or simple proposal?", "Big proposal", "Simple proposal"),
        ("Ring shopping together or full surprise?", "Shop together", "Full surprise"),
        ("Engagement photos or skip them?", "Take them", "Skip them"),
        ("Wedding vows traditional or self-written?", "Traditional", "Self-written"),
        ("First look before the ceremony or not?", "First look", "No first look"),
        ("Elope or big wedding?", "Elope", "Big wedding"),
        ("Wedding dance choreographed or freestyle?", "Choreographed", "Freestyle"),
        ("Honeymoon far away or nearby escape?", "Far away", "Nearby"),
        ("Honeymoon adventure or honeymoon relaxation?", "Adventure", "Relaxation"),
        ("Take each other's last name or keep yours?", "Take theirs", "Keep mine"),
        ("Hyphenated names or one name?", "Hyphenated", "One name"),
        ("Kids early or kids later?", "Early", "Later"),
        ("Kids or fur kids?", "Kids", "Fur kids"),
        ("Dog together or cat together?", "Dog", "Cat"),
        ("Big dog or small dog?", "Big dog", "Small dog"),
        ("Rescue pet or breeder pet?", "Rescue", "Breeder"),
        ("Pet in the bed or pet off the bed?", "In the bed", "Off the bed"),
        ("Grow old in the city or the countryside?", "City", "Countryside"),
        ("Retire by the sea or in the mountains?", "Sea", "Mountains"),
        ("Growing old gracefully or fighting it?", "Gracefully", "Fighting it"),
        ("Matching rocking chairs or garden bench?", "Rocking chairs", "Garden bench"),
        ("Renew vows someday or once is enough?", "Renew vows", "Once is enough"),
        ("Tell each other everything or some mystery forever?", "Everything", "Some mystery"),
        ("Argue about small things or save energy for big ones?", "Small things", "Big ones"),
        ("Never go to bed angry or take a pause?", "Never bed angry", "Take a pause"),
        ("Win the argument or win the relationship?", "Win argument", "Win relationship"),
        ("Scoreboard in fights or clean slate?", "Scoreboard", "Clean slate"),
        ("Jealousy is a compliment or a red flag?", "Compliment", "Red flag"),
        ("Partner's ex as friend or no contact?", "Friendly ex", "No contact"),
        ("Secrets between friends or tell your partner?", "Tell partner", "Keep secrets"),
        ("Crush on a celebrity: cute or off-limits?", "Cute", "Off-limits"),
        ("Flirty banter with others: harmless or not?", "Harmless", "Not okay"),
        ("Snooping through their phone or total trust?", "Total trust", "I'd snoop"),
        ("Share location with each other or not?", "Share location", "Don't share"),
        ("Check each other's search history or privacy?", "Privacy", "We check"),
        ("Social media couple name or individual handles?", "Couple name", "Individual"),
        ("Tag each other in memes all day or save the best one?", "All day", "Best one only"),
        ("Reply instantly or reply when free?", "Instantly", "When free"),
        ("Left on read: no big deal or a crime?", "No big deal", "A crime"),
        ("Double text or wait patiently?", "Double text", "Wait"),
        ("Voice notes or long texts?", "Voice notes", "Long texts"),
        ("Goodnight call or goodnight text?", "Call", "Text"),
        ("Fall asleep on call or hang up first?", "Fall asleep on call", "Hang up"),
        ("Their hoodies are yours now or ask first?", "Mine now", "Ask first"),
        ("Share headphones on the train or one each?", "Share", "One each"),
        ("Order the same meal or always different?", "Same meal", "Different"),
        ("Fight over the last slice or split it?", "Fight for it", "Split it"),
        ("Netflix profile share or separate?", "Share", "Separate"),
        ("Spoil the show or watch together?", "Never spoil", "We spoil"),
        ("Binge together or no-spoiler pact?", "Binge together", "No-spoiler pact"),
        ("Cry at movies together or hide the tears?", "Cry together", "Hide tears"),
        ("Scary movie cuddle or comedy night?", "Scary movie", "Comedy"),
        ("Watch sports together or shop together?", "Sports", "Shopping"),
        ("Their family recipes or yours?", "Theirs", "Mine"),
        ("Talk about your exes or leave the past?", "Talk about it", "Leave the past"),
        ("Counseling when things get hard or figure it out?", "Get counseling", "Figure it out"),
        ("Love is a feeling or a choice?", "A feeling", "A choice"),
        ("Soulmates are found or built?", "Found", "Built"),
        ("Fate brought you together or coincidence?", "Fate", "Coincidence"),
        ("Love at first sight or slow burn?", "Love at first sight", "Slow burn"),
        ("Opposites attract or birds of a feather?", "Opposites", "Feather flock"),
        ("The way to love is through the heart or the stomach?", "Heart", "Stomach"),
        ("Grand romantic gestures or steady devotion?", "Grand gestures", "Steady devotion"),
        ("Passion first or friendship first?", "Passion first", "Friendship first"),
        ("Distance makes the heart grow fonder or out of sight out of mind?", "Fonder", "Out of mind"),
        ("Absence of conflict or healthy conflict?", "Absence of conflict", "Healthy conflict"),
        ("Love means sacrifice or boundaries?", "Sacrifice", "Boundaries"),
        ("Happy partner or right partner?", "Happy partner", "Right partner"),
    ],

    "date-night": [
        ("Italian night or sushi night?", "Italian", "Sushi"),
        ("Rooftop dinner or garden dinner?", "Rooftop", "Garden"),
        ("Candlelight or string lights?", "Candlelight", "String lights"),
        ("Fine dining or hole-in-the-wall finds?", "Fine dining", "Hole-in-the-wall"),
        ("Tasting menu or à la carte?", "Tasting menu", "À la carte"),
        ("Dinner and a movie or just a long dinner?", "Dinner and movie", "Long dinner"),
        ("Dessert first or dessert last?", "First", "Last"),
        ("Share every dish or order your own?", "Share dishes", "Own dishes"),
        ("Wine pairing or cocktail flights?", "Wine pairing", "Cocktail flights"),
        ("Live jazz dinner or acoustic set?", "Jazz", "Acoustic"),
        ("Dinner cruise or dinner train?", "Cruise", "Train"),
        ("Cooking date at home or baking date at home?", "Cooking", "Baking"),
        ("Make pasta from scratch or pizza from scratch?", "Pasta", "Pizza"),
        ("Grill night or fondue night?", "Grill", "Fondue"),
        ("Taco Tuesday or pasta Friday?", "Tacos", "Pasta"),
        ("Brunch date or midnight snack date?", "Brunch", "Midnight snack"),
        ("Picnic under the stars or picnic by the lake?", "Stars", "Lake"),
        ("Sunset picnic or sunrise breakfast?", "Sunset", "Sunrise"),
        ("Drive-in movie or outdoor cinema?", "Drive-in", "Outdoor cinema"),
        ("Movie marathon or double feature?", "Marathon", "Double feature"),
        ("Classic film or new release?", "Classic", "New release"),
        ("Musical or play?", "Musical", "Play"),
        ("Opera or ballet?", "Opera", "Ballet"),
        ("Comedy show or magic show?", "Comedy", "Magic"),
        ("Open mic night or poetry slam?", "Open mic", "Poetry slam"),
        ("Karaoke bar or private karaoke room?", "Karaoke bar", "Private room"),
        ("Dancing at a club or dancing in the kitchen?", "Club", "Kitchen"),
        ("Salsa class or swing class?", "Salsa", "Swing"),
        ("Bowling or mini golf?", "Bowling", "Mini golf"),
        ("Arcade night or pinball bar?", "Arcade", "Pinball bar"),
        ("Escape room or murder mystery night?", "Escape room", "Murder mystery"),
        ("Casino night or game night?", "Casino", "Game night"),
        ("Poker night or chess night?", "Poker", "Chess"),
        ("Trivia night or quiz app at the bar?", "Trivia night", "Quiz app"),
        ("Paint and sip or pottery class?", "Paint and sip", "Pottery"),
        ("Photography walk or sketching date?", "Photography", "Sketching"),
        ("Museum after dark or planetarium show?", "Museum", "Planetarium"),
        ("Art gallery or sculpture garden?", "Gallery", "Sculpture garden"),
        ("Bookstore browsing or record store digging?", "Bookstore", "Record store"),
        ("Farmers market morning or flea market afternoon?", "Farmers market", "Flea market"),
        ("Stargazing with a telescope or naked eye?", "Telescope", "Naked eye"),
        ("Night hike or full-moon paddle?", "Night hike", "Moon paddle"),
        ("Bonfire or firefly catching?", "Bonfire", "Fireflies"),
        ("Ice skating or roller skating?", "Ice", "Roller"),
        ("Sledding date or snowball fight?", "Sledding", "Snowball fight"),
        ("Summer concert or winter concert?", "Summer", "Winter"),
        ("Music festival or intimate gig?", "Festival", "Intimate gig"),
        ("Symphony or street performers?", "Symphony", "Street performers"),
        ("Batting cages or driving range?", "Batting cages", "Driving range"),
        ("Rock climbing or bouldering date?", "Rock climbing", "Bouldering"),
        ("Kayak for two or tandem bike?", "Kayak", "Tandem bike"),
        ("Horseback riding or ATV trail?", "Horses", "ATV"),
        ("Hot springs or sauna date?", "Hot springs", "Sauna"),
        ("Couples spa day or massage exchange at home?", "Spa day", "Massage at home"),
        ("Wine tasting or brewery tour?", "Wine tasting", "Brewery"),
        ("Whiskey tasting or rum tasting?", "Whiskey", "Rum"),
        ("Coffee cupping or tea ceremony?", "Coffee cupping", "Tea ceremony"),
        ("Chocolate factory tour or cheese farm?", "Chocolate", "Cheese"),
        ("Food truck rally or night market?", "Food trucks", "Night market"),
        ("Street food tour or dessert crawl?", "Street food", "Dessert crawl"),
        ("Cooking competition at home or bake-off?", "Cook-off", "Bake-off"),
        ("DIY pizza night or DIY taco bar?", "Pizza", "Taco bar"),
        ("Breakfast for dinner or breakfast for breakfast?", "Breakfast for dinner", "Regular breakfast"),
        ("Fondue date or raclette night?", "Fondue", "Raclette"),
        ("Barbecue under the stars or tailgate party?", "BBQ", "Tailgate"),
        ("Coffee shop people-watching or people-watching at the park?", "Coffee shop", "Park"),
        ("Book café date or board game café?", "Book café", "Board game café"),
        ("Cat café or dog café?", "Cat café", "Dog café"),
        ("Aquarium date or botanical gardens?", "Aquarium", "Botanical gardens"),
        ("Zoo date or safari park?", "Zoo", "Safari park"),
        ("Butterfly house or aviary?", "Butterflies", "Birds"),
        ("Amusement park or water park?", "Amusement", "Water park"),
        ("Roller coaster first or carousel last?", "Roller coaster", "Carousel"),
        ("Ferris wheel at sunset or tunnel of love?", "Ferris wheel", "Tunnel of love"),
        ("Carnival games or carnival food?", "Games", "Food"),
        ("Haunted house or ghost tour?", "Haunted house", "Ghost tour"),
        ("Christmas lights drive or haunted hayride?", "Christmas lights", "Hayride"),
        ("Ice cream walk or donut run?", "Ice cream", "Donuts"),
        ("Late-night diner or 24-hour bakery?", "Diner", "Bakery"),
        ("Midnight movie or midnight bakery run?", "Midnight movie", "Bakery run"),
        ("Stroll the old town or explore a new district?", "Old town", "New district"),
        ("Tourist in your own city or hidden local spots?", "Tourist mode", "Local spots"),
        ("Weekend getaway or staycation?", "Weekend getaway", "Staycation"),
        ("Cabin in the woods or lodge by the lake?", "Cabin", "Lodge"),
        ("Glamping trip or boutique hotel?", "Glamping", "Boutique hotel"),
        ("Bed and breakfast or Airbnb with a view?", "B&B", "Airbnb"),
        ("Sunset sail or sunrise hot air balloon?", "Sail", "Balloon"),
        ("Helicopter tour or seaplane tour?", "Helicopter", "Seaplane"),
        ("Train through the mountains or coastal drive?", "Train", "Coastal drive"),
        ("Convertible or motorcycle for a date drive?", "Convertible", "Motorcycle"),
        ("Horse-drawn carriage or vintage car rental?", "Carriage", "Vintage car"),
        ("Scavenger hunt date or treasure hunt clues?", "Scavenger hunt", "Treasure hunt"),
        ("Recreate your first date or dream up a new tradition?", "Recreate", "New tradition"),
        ("Memory lane tour or future-planning date?", "Memory lane", "Future planning"),
        ("Question card games or deep conversation walk?", "Card games", "Conversation walk"),
        ("Couples journaling or couples meditation?", "Journaling", "Meditation"),
        ("Sunrise yoga date or gym buddy date?", "Yoga", "Gym"),
        ("Volunteer together or take a class together?", "Volunteer", "Class"),
        ("Learn a language together or an instrument?", "Language", "Instrument"),
        ("Plant a garden together or adopt a plant?", "Garden", "Adopt a plant"),
        ("Stargaze from the roof or from a field?", "Roof", "Field"),
        ("Meteor shower watch or eclipse watch?", "Meteor shower", "Eclipse"),
        ("Puzzle night with jazz or puzzle night in silence?", "With jazz", "Silence"),
        ("Documentary night or stand-up special?", "Documentary", "Stand-up"),
        ("Reality show binge or film trilogy night?", "Reality TV", "Trilogy"),
        ("Rewatch an old favorite or finally start the new show?", "Rewatch", "New show"),
        ("Firepit s'mores or fondue by the fire?", "S'mores", "Fondue"),
        ("Birthday date: surprise party or intimate dinner?", "Surprise party", "Intimate dinner"),
        ("Valentine's fancy or Valentine's cozy?", "Fancy", "Cozy"),
        ("Date budget: many cheap dates or few lux dates?", "Many cheap", "Few luxe"),
    ],

    "deep-talks": [
        ("Success or happiness?", "Success", "Happiness"),
        ("Fame or fortune?", "Fame", "Fortune"),
        ("Money or meaning?", "Money", "Meaning"),
        ("Passion or stability?", "Passion", "Stability"),
        ("Ambition or contentment?", "Ambition", "Contentment"),
        ("Adventure or security?", "Adventure", "Security"),
        ("Freedom or belonging?", "Freedom", "Belonging"),
        ("Truth or kindness?", "Truth", "Kindness"),
        ("Honesty even when hard or white lies for peace?", "Honesty", "White lies"),
        ("Justice or mercy?", "Justice", "Mercy"),
        ("Revenge or forgiveness?", "Revenge", "Forgiveness"),
        ("Regret doing or regret not trying?", "Doing", "Not trying"),
        ("Live fast or live long?", "Fast", "Long"),
        ("Depth of knowledge or breadth of experience?", "Depth", "Breadth"),
        ("Wisdom or intelligence?", "Wisdom", "Intelligence"),
        ("Talent or hard work?", "Talent", "Hard work"),
        ("Luck or preparation?", "Luck", "Preparation"),
        ("Destiny or choice?", "Destiny", "Choice"),
        ("Everything happens for a reason or random chance?", "For a reason", "Random"),
        ("The journey or the destination?", "Journey", "Destination"),
        ("The process or the result?", "Process", "Result"),
        ("Perfection or progress?", "Perfection", "Progress"),
        ("Being liked or being respected?", "Liked", "Respected"),
        ("Being right or being happy?", "Right", "Happy"),
        ("Being feared or being loved?", "Feared", "Loved"),
        ("Popularity or authenticity?", "Popularity", "Authenticity"),
        ("Impressing others or pleasing yourself?", "Impress others", "Please yourself"),
        ("Solitude or society?", "Solitude", "Society"),
        ("Many acquaintances or few close friends?", "Many acquaintances", "Few close"),
        ("Old friends or new friends?", "Old", "New"),
        ("Family by blood or family by choice?", "Blood", "Choice"),
        ("Loyalty or honesty?", "Loyalty", "Honesty"),
        ("Trust easily or earn it slowly?", "Easily", "Slowly"),
        ("Second chances or three strikes?", "Second chances", "Three strikes"),
        ("Forget or remember?", "Forget", "Remember"),
        ("Nostalgia or anticipation?", "Nostalgia", "Anticipation"),
        ("Past or future?", "Past", "Future"),
        ("Live in the moment or plan ahead?", "The moment", "Plan ahead"),
        ("Youth or experience?", "Youth", "Experience"),
        ("Innocence or awareness?", "Innocence", "Awareness"),
        ("Hope or realism?", "Hope", "Realism"),
        ("Optimist or pessimist?", "Optimist", "Pessimist"),
        ("Cynic or dreamer?", "Cynic", "Dreamer"),
        ("Idealist or pragmatist?", "Idealist", "Pragmatist"),
        ("Head or heart?", "Head", "Heart"),
        ("Logic or intuition?", "Logic", "Intuition"),
        ("Facts or feelings?", "Facts", "Feelings"),
        ("Think fast or think deep?", "Fast", "Deep"),
        ("Silence or conversation?", "Silence", "Conversation"),
        ("Big talk or small talk?", "Big talk", "Small talk"),
        ("Listen more or speak more?", "Listen", "Speak"),
        ("Ask questions or give answers?", "Ask", "Answer"),
        ("Change the world or change yourself?", "The world", "Yourself"),
        ("Lead or follow?", "Lead", "Follow"),
        ("Stand out or blend in?", "Stand out", "Blend in"),
        ("Fight or flight?", "Fight", "Flight"),
        ("Confront or avoid?", "Confront", "Avoid"),
        ("Push through or step back?", "Push through", "Step back"),
        ("Control or surrender?", "Control", "Surrender"),
        ("Plan A or plan B?", "Plan A", "Plan B"),
        ("Rules or exceptions?", "Rules", "Exceptions"),
        ("Tradition or innovation?", "Tradition", "Innovation"),
        ("Roots or wings?", "Roots", "Wings"),
        ("Home or away?", "Home", "Away"),
        ("Stay or go?", "Stay", "Go"),
        ("Beginnings or endings?", "Beginnings", "Endings"),
        ("Hello or goodbye?", "Hello", "Goodbye"),
        ("First impression or last impression?", "First", "Last"),
        ("Reputation or character?", "Reputation", "Character"),
        ("What you say or how you say it?", "What", "How"),
        ("Actions or words?", "Actions", "Words"),
        ("Promises or vibes?", "Promises", "Vibes"),
        ("Growth or comfort?", "Growth", "Comfort"),
        ("Discipline or motivation?", "Discipline", "Motivation"),
        ("Rest or hustle?", "Rest", "Hustle"),
        ("Slow and steady or fast and fierce?", "Slow and steady", "Fast and fierce"),
        ("Work to live or live to work?", "Work to live", "Live to work"),
        ("Rich in money or rich in time?", "Money", "Time"),
        ("Spend or save?", "Spend", "Save"),
        ("Give or receive?", "Give", "Receive"),
        ("Generosity or frugality?", "Generosity", "Frugality"),
        ("Charity begins at home or everywhere?", "At home", "Everywhere"),
        ("Karma or coincidence?", "Karma", "Coincidence"),
        ("Faith or science?", "Faith", "Science"),
        ("Soul or matter?", "Soul", "Matter"),
        ("Afterlife or here and now?", "Afterlife", "Here and now"),
        ("Meaning is found or made?", "Found", "Made"),
        ("Happiness is a state or a pursuit?", "A state", "A pursuit"),
        ("Suffering teaches or scars?", "Teaches", "Scars"),
        ("Pain is weakness leaving or damage done?", "Weakness leaving", "Damage"),
        ("Fear protects or limits?", "Protects", "Limits"),
        ("Courage or caution?", "Courage", "Caution"),
        ("Risk it all or protect what you have?", "Risk it all", "Protect"),
        ("Dream big or dream real?", "Big", "Real"),
        ("Follow your dreams or follow the money?", "Dreams", "Money"),
        ("Career or calling?", "Career", "Calling"),
        ("Legacy or memories?", "Legacy", "Memories"),
        ("Be remembered or be forgotten?", "Remembered", "Forgotten quietly"),
        ("Fame for a moment or impact for a lifetime?", "Moment of fame", "Lifelong impact"),
        ("Change one life deeply or many lives lightly?", "One deeply", "Many lightly"),
        ("Love deeply or love safely?", "Deeply", "Safely"),
        ("Better to have loved and lost or never loved?", "Loved and lost", "Never loved"),
        ("Lonely alone or lonely together?", "Alone", "Together"),
        ("Grow old or stay young at heart?", "Grow old", "Young at heart"),
        ("Peace or excitement?", "Peace", "Excitement"),
        ("Simple life or full life?", "Simple", "Full"),
        ("More possessions or more experiences?", "Possessions", "Experiences"),
        ("Bucket list or go with the flow?", "Bucket list", "Go with the flow"),
        ("Regrets of action or regrets of inaction?", "Action", "Inaction"),
    ],

    "future-us": [
        ("House or apartment?", "House", "Apartment"),
        ("City or suburbs?", "City", "Suburbs"),
        ("Countryside or coast?", "Countryside", "Coast"),
        ("Old charmer or new build?", "Old charmer", "New build"),
        ("Tiny house or big house?", "Tiny", "Big"),
        ("Garden or pool?", "Garden", "Pool"),
        ("Home office or home gym?", "Home office", "Home gym"),
        ("Open-plan or separate rooms?", "Open-plan", "Separate rooms"),
        ("Big kitchen or big bathroom?", "Big kitchen", "Big bathroom"),
        ("Balcony or backyard?", "Balcony", "Backyard"),
        ("Fireplace or home cinema?", "Fireplace", "Home cinema"),
        ("Renovate a fixer or move-in ready?", "Fixer-upper", "Move-in ready"),
        ("Rent long-term or buy soon?", "Rent", "Buy"),
        ("Stay in one place forever or move around?", "Forever home", "Move around"),
        ("Move abroad someday or stay close to home?", "Move abroad", "Stay close"),
        ("Raise kids in the city or the country?", "City", "Country"),
        ("Kids close in age or spread out?", "Close in age", "Spread out"),
        ("Two kids or three?", "Two", "Three"),
        ("Kids or travel the world?", "Kids", "Travel"),
        ("Family pet first or kids first?", "Pet first", "Kids first"),
        ("Minivan or SUV?", "Minivan", "SUV"),
        ("Family bike rides or family hikes?", "Bike rides", "Hikes"),
        ("Summer at the lake or summer at the beach?", "Lake", "Beach"),
        ("Christmas at home or Christmas traveling?", "At home", "Traveling"),
        ("Host the holidays or visit for the holidays?", "Host", "Visit"),
        ("Family traditions old or invented?", "Old traditions", "Invented ones"),
        ("Sunday roasts or Sunday takeout?", "Roasts", "Takeout"),
        ("Family game night or family movie night?", "Game night", "Movie night"),
        ("Read to the kids or build with the kids?", "Read", "Build"),
        ("Strict parents or chill parents?", "Strict", "Chill"),
        ("Kids' screen time limited or unlimited?", "Limited", "Unlimited"),
        ("Save for college or let them figure it out?", "Save for college", "They figure it out"),
        ("Retire early or work forever on your terms?", "Retire early", "Work on my terms"),
        ("Retire near the kids or retire somewhere warm?", "Near the kids", "Somewhere warm"),
        ("Pension plan or investment portfolio?", "Pension", "Portfolio"),
        ("Safe savings or risky investments?", "Safe", "Risky"),
        ("Emergency fund or live for today?", "Emergency fund", "Live today"),
        ("Budget together or budget separately?", "Together", "Separately"),
        ("Financial advisor or DIY finances?", "Advisor", "DIY"),
        ("One day: boat or camper?", "Boat", "Camper"),
        ("Grow your own food or shop local?", "Grow your own", "Shop local"),
        ("Solar panels or smart home first?", "Solar", "Smart home"),
        ("Electric car or keep it old-school?", "Electric", "Old-school"),
        ("Learn to sail or learn to fly?", "Sail", "Fly"),
        ("Second language for the family or music lessons?", "Language", "Music"),
        ("Write a book or start a business?", "Book", "Business"),
        ("Side hustle or work-life balance?", "Side hustle", "Balance"),
        ("Climb the ladder or build the ladder?", "Climb it", "Build it"),
        ("Follow the job or make the job follow you?", "Follow the job", "Job follows me"),
        ("Sabbatical year or steady climb?", "Sabbatical", "Steady climb"),
        ("Wedding: big party or small ceremony?", "Big party", "Small ceremony"),
        ("Wedding: destination or hometown?", "Destination", "Hometown"),
        ("Wedding: summer or winter?", "Summer", "Winter"),
        ("Wedding: band or DJ?", "Band", "DJ"),
        ("Wedding: sit-down dinner or food stations?", "Sit-down", "Stations"),
        ("Honeymoon: island or mountains?", "Island", "Mountains"),
        ("Honeymoon: one big trip or several small ones?", "One big", "Several small"),
        ("Vows: classic or handwritten?", "Classic", "Handwritten"),
        ("Wedding photos: traditional or candid?", "Traditional", "Candid"),
        ("Keep the surname traditions or make your own?", "Traditions", "Our own"),
        ("Anniversary trips every year or a big one every five?", "Every year", "Every five"),
        ("Growing old: porch swing or garden bench?", "Porch swing", "Garden bench"),
        ("Matching slippers or matching reading glasses?", "Slippers", "Reading glasses"),
        ("Retirement hobby: gardening or golfing?", "Gardening", "Golfing"),
        ("Retirement: near grandkids or near the sea?", "Grandkids", "The sea"),
        ("Time capsule or family tree project?", "Time capsule", "Family tree"),
        ("Future you: wiser or richer?", "Wiser", "Richer"),
        ("Future you: braver or calmer?", "Braver", "Calmer"),
        ("Ten years from now: same city or somewhere new?", "Same city", "Somewhere new"),
        ("Dream big or plan small?", "Dream big", "Plan small"),
        ("Life plan detailed or loosely sketched?", "Detailed", "Loose"),
        ("Five-year plan or five-year vibe?", "Plan", "Vibe"),
        ("Settle down early or explore first?", "Settle early", "Explore first"),
        ("Bucket list long or short?", "Long", "Short"),
        ("One house for life or a new house each decade?", "One for life", "Each decade"),
        ("Heirlooms to pass down or stories to pass down?", "Heirlooms", "Stories"),
        ("Family name carried on or new names invented?", "Carried on", "Invented"),
        ("Volunteer more later or start now?", "Later", "Now"),
        ("Learn an instrument at 60 or a language at 60?", "Instrument", "Language"),
        ("Marathon someday or marathon never?", "Someday", "Never"),
        ("See the northern lights or the pyramids?", "Northern lights", "Pyramids"),
        ("World tour or deep roots?", "World tour", "Deep roots"),
        ("Live by the mountains or by the sea?", "Mountains", "Sea"),
        ("Someday: farmhouse or penthouse?", "Farmhouse", "Penthouse"),
        ("Campervan life or cottage life?", "Campervan", "Cottage"),
        ("Off the grid or fully connected?", "Off-grid", "Connected"),
        ("Grow old with adventures or with routines?", "Adventures", "Routines"),
        ("Legacy: what you built or who you loved?", "What you built", "Who you loved"),
    ],
}
