"""Seed questions: food, travel, lifestyle, home.
Format: {category_id: [(prompt, option1, option2), ...]}
"""

SEED = {
    "food-drink": [
        ("Pancakes or waffles?", "Pancakes", "Waffles"),
        ("Bagel or croissant?", "Bagel", "Croissant"),
        ("Scrambled or fried eggs?", "Scrambled", "Fried"),
        ("Oatmeal or yogurt bowl?", "Oatmeal", "Yogurt bowl"),
        ("Espresso or filter coffee?", "Espresso", "Filter"),
        ("Latte or cappuccino?", "Latte", "Cappuccino"),
        ("Iced latte or frappe?", "Iced latte", "Frappe"),
        ("Matcha or chai?", "Matcha", "Chai"),
        ("Green tea or black tea?", "Green", "Black"),
        ("Bubble tea or smoothie?", "Bubble tea", "Smoothie"),
        ("Lemonade or iced tea?", "Lemonade", "Iced tea"),
        ("Sparkling or still water?", "Sparkling", "Still"),
        ("Orange juice or apple juice?", "Orange", "Apple"),
        ("Milkshake or malt?", "Milkshake", "Malt"),
        ("Hot cocoa or mulled cider?", "Cocoa", "Cider"),
        ("Red wine or white wine?", "Red", "White"),
        ("Beer or cider?", "Beer", "Cider"),
        ("Cocktail or mocktail?", "Cocktail", "Mocktail"),
        ("Mojito or margarita?", "Mojito", "Margarita"),
        ("Whiskey sour or old fashioned?", "Whiskey sour", "Old fashioned"),
        ("Aperol spritz or negroni?", "Spritz", "Negroni"),
        ("Burger or hot dog?", "Burger", "Hot dog"),
        ("Cheeseburger or veggie burger?", "Cheese", "Veggie"),
        ("Fries or onion rings?", "Fries", "Onion rings"),
        ("Ketchup or mayo?", "Ketchup", "Mayo"),
        ("Guacamole or hummus?", "Guacamole", "Hummus"),
        ("Salsa or queso?", "Salsa", "Queso"),
        ("Nachos or quesadilla?", "Nachos", "Quesadilla"),
        ("Burrito or burrito bowl?", "Burrito", "Bowl"),
        ("Ramen or pho?", "Ramen", "Pho"),
        ("Pad thai or pad see ew?", "Pad thai", "Pad see ew"),
        ("Dumplings or spring rolls?", "Dumplings", "Spring rolls"),
        ("Sushi rolls or sashimi?", "Rolls", "Sashimi"),
        ("Rice or noodles?", "Rice", "Noodles"),
        ("Curry mild or curry fiery?", "Mild", "Fiery"),
        ("Butter chicken or tikka masala?", "Butter chicken", "Tikka masala"),
        ("Naan or roti?", "Naan", "Roti"),
        ("Falafel or shawarma?", "Falafel", "Shawarma"),
        ("Kebab or gyro?", "Kebab", "Gyro"),
        ("Paella or risotto?", "Paella", "Risotto"),
        ("Lasagna or spaghetti bolognese?", "Lasagna", "Spaghetti"),
        ("Alfredo or marinara?", "Alfredo", "Marinara"),
        ("Pesto or arrabbiata?", "Pesto", "Arrabbiata"),
        ("Mac and cheese or mashed potatoes?", "Mac and cheese", "Mashed potatoes"),
        ("Baked potato or roast potatoes?", "Baked", "Roast"),
        ("Soup or salad?", "Soup", "Salad"),
        ("Tomato soup or chicken noodle?", "Tomato", "Chicken noodle"),
        ("Chowder or bisque?", "Chowder", "Bisque"),
        ("Caesar or Greek salad?", "Caesar", "Greek"),
        ("Croutons or no croutons?", "Croutons", "None"),
        ("Steak rare or well done?", "Rare", "Well done"),
        ("Ribs or brisket?", "Ribs", "Brisket"),
        ("Fried chicken or roast chicken?", "Fried", "Roast"),
        ("Wings: buffalo or BBQ?", "Buffalo", "BBQ"),
        ("Seafood or steakhouse?", "Seafood", "Steakhouse"),
        ("Lobster or crab?", "Lobster", "Crab"),
        ("Shrimp or scallops?", "Shrimp", "Scallops"),
        ("Oysters or mussels?", "Oysters", "Mussels"),
        ("Fish and chips or fish tacos?", "Fish and chips", "Fish tacos"),
        ("Squid or octopus?", "Squid", "Octopus"),
        ("Breakfast burrito or breakfast sandwich?", "Burrito", "Sandwich"),
        ("French toast or eggs benedict?", "French toast", "Eggs benedict"),
        ("Crepes or croissants?", "Crepes", "Croissants"),
        ("Brunch buffet or brunch à la carte?", "Buffet", "À la carte"),
        ("Avocado toast or peanut butter toast?", "Avocado", "Peanut butter"),
        ("Honey or jam?", "Honey", "Jam"),
        ("Peanut butter or nutella?", "Peanut butter", "Nutella"),
        ("Cheese plate or charcuterie board?", "Cheese", "Charcuterie"),
        ("Brie or cheddar?", "Brie", "Cheddar"),
        ("Feta or mozzarella?", "Feta", "Mozzarella"),
        ("Blue cheese or goat cheese?", "Blue", "Goat"),
        ("Chocolate cake or cheesecake?", "Chocolate cake", "Cheesecake"),
        ("Brownies or blondies?", "Brownies", "Blondies"),
        ("Cookies or brownies?", "Cookies", "Brownies"),
        ("Apple pie or pecan pie?", "Apple", "Pecan"),
        ("Pumpkin pie or key lime pie?", "Pumpkin", "Key lime"),
        ("Tiramisu or crème brûlée?", "Tiramisu", "Crème brûlée"),
        ("Gelato or sorbet?", "Gelato", "Sorbet"),
        ("Sundae or banana split?", "Sundae", "Banana split"),
        ("Soft serve or hard ice cream?", "Soft", "Hard"),
        ("Popsicle or ice cream sandwich?", "Popsicle", "Sandwich"),
        ("Candy sour or candy sweet?", "Sour", "Sweet"),
        ("Gummies or hard candy?", "Gummies", "Hard candy"),
        ("Chocolate: dark or white?", "Dark", "White"),
        ("Marshmallows toasted or raw?", "Toasted", "Raw"),
        ("S'mores or rice crispy treats?", "S'mores", "Rice crispy"),
        ("Popcorn sweet or salty?", "Sweet", "Salty"),
        ("Movie snacks: popcorn or candy?", "Popcorn", "Candy"),
        ("Pretzels or chips?", "Pretzels", "Chips"),
        ("Tortilla chips: plain or flavored?", "Plain", "Flavored"),
        ("Trail mix or granola bars?", "Trail mix", "Granola bars"),
        ("Almonds or cashews?", "Almonds", "Cashews"),
        ("Pistachios or peanuts?", "Pistachios", "Peanuts"),
        ("Dinner early or dinner late?", "Early", "Late"),
        ("Snack at midnight or breakfast at dawn?", "Midnight snack", "Dawn breakfast"),
        ("Cook with garlic or cook with onion?", "Garlic", "Onion"),
        ("Spicy everything or mild everything?", "Spicy", "Mild"),
        ("Hot sauce on everything or no hot sauce?", "Everything", "None"),
        ("Salt or sugar rim?", "Salt", "Sugar"),
        ("Butter or olive oil?", "Butter", "Olive oil"),
        ("Grill with charcoal or gas?", "Charcoal", "Gas"),
        ("Slow cooker or air fryer?", "Slow cooker", "Air fryer"),
        ("Meal prep Sunday or cook fresh daily?", "Meal prep", "Fresh daily"),
        ("Recipe follower or freestyle cook?", "Recipe", "Freestyle"),
        ("Bake bread or bake cookies?", "Bread", "Cookies"),
        ("Homemade pizza or delivery pizza?", "Homemade", "Delivery"),
        ("Food truck or food court?", "Food truck", "Food court"),
        ("Dine solo or dine with a crowd?", "Solo", "Crowd"),
        ("Tasting menu or buffet?", "Tasting menu", "Buffet"),
        ("Leftovers for lunch or fresh lunch?", "Leftovers", "Fresh"),
        ("Brunch on Saturday or Sunday?", "Saturday", "Sunday"),
        ("Coffee after dinner or dessert after dinner?", "Coffee", "Dessert"),
        ("Decaf after dark or full power always?", "Decaf", "Full power"),
        ("One perfect meal or endless snacks?", "One perfect meal", "Endless snacks"),
        ("Breakfast all day or dessert all day?", "Breakfast", "Dessert"),
        ("Comfort food or adventurous food?", "Comfort", "Adventurous"),
        ("Street food abroad or fancy restaurant abroad?", "Street food", "Fancy"),
        ("Try the local delicacy or stick to the menu?", "Delicacy", "Safe menu"),
        ("Spicy challenge or sweet challenge?", "Spicy", "Sweet"),
        ("Share plates or own plates?", "Share", "Own"),
        ("Eat to live or live to eat?", "Eat to live", "Live to eat"),
    ],

    "travel": [
        ("Window seat or middle of the aisle train?", "Window seat", "Aisle seat"),
        ("Beach holiday or city break?", "Beach", "City"),
        ("Somewhere hot or somewhere cold?", "Hot", "Cold"),
        ("Tropical island or snowy lodge?", "Tropical", "Snowy"),
        ("Backpack or rolling suitcase?", "Backpack", "Suitcase"),
        ("Carry-on only or check a bag?", "Carry-on", "Checked bag"),
        ("Travel pillow or eye mask?", "Pillow", "Eye mask"),
        ("Red-eye flight or crack-of-dawn flight?", "Red-eye", "Crack of dawn"),
        ("Train travel or bus travel?", "Train", "Bus"),
        ("Ferry or flight?", "Ferry", "Flight"),
        ("Road trip with playlists or road trip with podcasts?", "Playlists", "Podcasts"),
        ("Scenic route or fastest route?", "Scenic", "Fastest"),
        ("Stop at every viewpoint or drive straight through?", "Every stop", "Straight through"),
        ("Plan each hour or wing it entirely?", "Plan hourly", "Wing it"),
        ("Itinerary app or paper map?", "App", "Paper map"),
        ("Guidebook or blog research?", "Guidebook", "Blogs"),
        ("Tourist landmarks or local hangouts?", "Landmarks", "Local spots"),
        ("Museums or markets?", "Museums", "Markets"),
        ("Cathedral tours or castle tours?", "Cathedrals", "Castles"),
        ("Skyline from a tower or skyline from a boat?", "Tower", "Boat"),
        ("Sunrise at the summit or sunset on the shore?", "Summit sunrise", "Shore sunset"),
        ("Snorkeling or scuba diving?", "Snorkeling", "Scuba"),
        ("Surfing or paddleboarding?", "Surfing", "Paddleboarding"),
        ("Sailing or motorboating?", "Sailing", "Motorboat"),
        ("Kayak or canoe?", "Kayak", "Canoe"),
        ("Zip-lining or bungee jumping?", "Zip-line", "Bungee"),
        ("Skiing or snowboarding?", "Skiing", "Snowboarding"),
        ("Sledding or snowshoeing?", "Sledding", "Snowshoeing"),
        ("Ice hotel or treehouse hotel?", "Ice hotel", "Treehouse"),
        ("Hostel dorm or private room?", "Dorm", "Private room"),
        ("Camping under stars or camper van?", "Under stars", "Camper van"),
        ("Tent or hammock?", "Tent", "Hammock"),
        ("Campfire cooking or trail snacks?", "Campfire cooking", "Trail snacks"),
        ("Mountain cabin or desert retreat?", "Mountain", "Desert"),
        ("Rainforest trek or savanna safari?", "Rainforest", "Savanna"),
        ("Northern lights or southern stars?", "Northern lights", "Southern stars"),
        ("Aurora hunting or meteor watching?", "Aurora", "Meteors"),
        ("Japan in spring or Japan in autumn?", "Spring", "Autumn"),
        ("Paris or Rome?", "Paris", "Rome"),
        ("London or New York?", "London", "New York"),
        ("Barcelona or Lisbon?", "Barcelona", "Lisbon"),
        ("Amsterdam or Prague?", "Amsterdam", "Prague"),
        ("Iceland or Ireland?", "Iceland", "Ireland"),
        ("Greece or Croatia?", "Greece", "Croatia"),
        ("Morocco or Egypt?", "Morocco", "Egypt"),
        ("Kenya or Tanzania?", "Kenya", "Tanzania"),
        ("Thailand or Vietnam?", "Thailand", "Vietnam"),
        ("Bali or the Maldives?", "Bali", "Maldives"),
        ("Australia or New Zealand?", "Australia", "New Zealand"),
        ("Peru or Patagonia?", "Peru", "Patagonia"),
        ("Canada or Alaska?", "Canada", "Alaska"),
        ("Caribbean cruise or Mediterranean cruise?", "Caribbean", "Mediterranean"),
        ("Round-the-world ticket or one deep trip?", "Round the world", "One deep trip"),
        ("Digital nomad life or annual big trip?", "Nomad life", "Annual trip"),
        ("Travel for food or travel for views?", "Food", "Views"),
        ("Travel for history or travel for nightlife?", "History", "Nightlife"),
        ("Festival abroad or quiet escape abroad?", "Festival", "Quiet escape"),
        ("Carnival in Rio or Oktoberfest in Munich?", "Rio", "Munich"),
        ("Full moon party or lantern festival?", "Full moon", "Lanterns"),
        ("Cherry blossoms or autumn leaves?", "Cherry blossoms", "Autumn leaves"),
        ("Desert stargazing or bioluminescent bay?", "Desert stars", "Glowing bay"),
        ("Hot springs in snow or hot springs in jungle?", "In snow", "In jungle"),
        ("Volcano hike or glacier walk?", "Volcano", "Glacier"),
        ("Waterfall chase or lake day?", "Waterfalls", "Lake day"),
        ("Stay in the old town or the new district?", "Old town", "New district"),
        ("Boutique hotel or chain hotel?", "Boutique", "Chain"),
        ("Airbnb with a kitchen or hotel with breakfast?", "Airbnb", "Hotel breakfast"),
        ("Room with a view or room with a pool?", "View", "Pool"),
        ("Rooftop bar or basement jazz club?", "Rooftop", "Jazz club"),
        ("Street food crawl or fine dining night?", "Street crawl", "Fine dining"),
        ("Cooking class abroad or photography tour?", "Cooking class", "Photo tour"),
        ("Language crash course or translation app?", "Crash course", "App"),
        ("Souvenirs for everyone or just a magnet?", "For everyone", "Just a magnet"),
        ("Travel journal or Instagram stories?", "Journal", "Stories"),
        ("Print your photos or leave them digital?", "Print", "Digital"),
        ("Postcards or no mail at all?", "Postcards", "None"),
        ("Jet lag: push through or nap it out?", "Push through", "Nap"),
        ("Airport lounge or terminal bench?", "Lounge", "Bench"),
        ("Airport arrival early or cutting it close?", "Very early", "Cutting close"),
        ("TSA line small talk or silent shuffle?", "Small talk", "Silent"),
        ("First class someday or more trips in economy?", "First class once", "More trips"),
        ("Travel insurance always or risk it?", "Always", "Risk it"),
        ("Local SIM or international roaming?", "Local SIM", "Roaming"),
        ("Cash or card abroad?", "Cash", "Card"),
        ("Haggle at markets or pay the price?", "Haggle", "Pay up"),
        ("Tuk-tuk or taxi?", "Tuk-tuk", "Taxi"),
        ("Rent a scooter or rent a bike?", "Scooter", "Bike"),
        ("Hop-on bus or walking tour?", "Hop-on bus", "Walking tour"),
        ("Segway tour or bike tour?", "Segway", "Bike"),
        ("Museum all day or museum one hour?", "All day", "One hour"),
        ("Skip the line tickets or spontaneous entry?", "Skip-the-line", "Spontaneous"),
        ("Group tour or private guide?", "Group", "Private"),
        ("Volunteer trip or wellness retreat?", "Volunteer", "Wellness"),
        ("Yoga retreat or hiking retreat?", "Yoga", "Hiking"),
        ("Spa weekend or adventure weekend?", "Spa", "Adventure"),
        ("Staycation at home or staycation in a hotel?", "At home", "Hotel"),
        ("One weekend trip a month or one month-long trip a year?", "Monthly weekends", "Annual month"),
        ("Explore your own country or the whole world?", "Own country", "Whole world"),
        ("Anywhere with wifi or anywhere without?", "With wifi", "Without"),
        ("Travel solo once or never travel solo?", "Once", "Never"),
        ("Meet strangers abroad or keep to yourselves?", "Meet strangers", "Keep to us"),
        ("Learn the history before or after the trip?", "Before", "After"),
        ("Return to favorites or always somewhere new?", "Return", "New"),
    ],

    "lifestyle": [
        ("Alarm across the room or alarm by the bed?", "Across the room", "By the bed"),
        ("Snooze once or never snooze?", "Snooze once", "Never"),
        ("Shower at night or shower in the morning?", "Night", "Morning"),
        ("Cold showers or hot showers?", "Cold", "Hot"),
        ("Bath bombs or bubbles?", "Bath bombs", "Bubbles"),
        ("Skincare three steps or ten steps?", "Three", "Ten"),
        ("Makeup everyday or special occasions?", "Everyday", "Occasions"),
        ("Perfume or body spray?", "Perfume", "Body spray"),
        ("Hair up or hair down?", "Up", "Down"),
        ("Beard or clean shaven?", "Beard", "Clean shaven"),
        ("Long hair or short hair?", "Long", "Short"),
        ("Piercings or tattoos?", "Piercings", "Tattoos"),
        ("One tattoo or many?", "One", "Many"),
        ("Gym membership or home equipment?", "Gym", "Home"),
        ("Morning run or evening run?", "Morning", "Evening"),
        ("Treadmill or trail?", "Treadmill", "Trail"),
        ("Lifting or cardio?", "Lifting", "Cardio"),
        ("Yoga or pilates morning?", "Yoga", "Pilates"),
        ("Meditation app or silent sit?", "App", "Silent"),
        ("Journaling morning or journaling night?", "Morning", "Night"),
        ("Gratitude list or to-do list first thing?", "Gratitude", "To-do"),
        ("Digital detox weekly or never?", "Weekly", "Never"),
        ("Phone in the bedroom or outside?", "In bedroom", "Outside"),
        ("Screen time limits or free rein?", "Limits", "Free rein"),
        ("News in the morning or news at night?", "Morning", "Night"),
        ("Podcasts on the commute or music?", "Podcasts", "Music"),
        ("Audiobooks or ebooks?", "Audiobooks", "Ebooks"),
        ("Read fiction or nonfiction?", "Fiction", "Nonfiction"),
        ("Library loyalist or bookstore buyer?", "Library", "Bookstore"),
        ("Kindle or paperback?", "Kindle", "Paperback"),
        ("Read one book at a time or five?", "One", "Five"),
        ("Finish every book or quit freely?", "Finish", "Quit freely"),
        ("Movie at home or movie out?", "Home", "Out"),
        ("Subtitles always or never?", "Always", "Never"),
        ("Binge a season in a weekend or savor weekly?", "Binge", "Weekly"),
        ("Rewatch favorites or new releases?", "Rewatch", "New"),
        ("Reality TV or documentaries?", "Reality", "Documentaries"),
        ("True crime or comedy specials?", "True crime", "Comedy"),
        ("Horror movies or thrillers?", "Horror", "Thriller"),
        ("Video games solo or co-op?", "Solo", "Co-op"),
        ("Console or PC gaming?", "Console", "PC"),
        ("Mobile games or board games?", "Mobile", "Board"),
        ("Puzzle games or action games?", "Puzzle", "Action"),
        ("Garden or houseplants?", "Garden", "Houseplants"),
        ("Cooking as hobby or cooking as chore?", "Hobby", "Chore"),
        ("Baking bread or baking cakes?", "Bread", "Cakes"),
        ("Sunday reset or Sunday rest?", "Reset", "Rest"),
        ("Deep clean weekends or little-and-often?", "Weekend deep clean", "Little and often"),
        ("Marie Kondo or organized chaos?", "Kondo", "Chaos"),
        ("To-do apps or paper lists?", "Apps", "Paper"),
        ("Calendar color-coded or bare?", "Color-coded", "Bare"),
        ("Inbox zero or inbox thousands?", "Zero", "Thousands"),
        ("Email notifications on or off?", "On", "Off"),
        ("Instant replies or batch replies?", "Instant", "Batched"),
        ("Voice messages or typing?", "Voice", "Typing"),
        ("Phone calls or video calls?", "Phone", "Video"),
        ("Social media daily or rarely?", "Daily", "Rarely"),
        ("Post everything or lurk quietly?", "Post", "Lurk"),
        ("Close friends story or public story?", "Close friends", "Public"),
        ("Dating apps or meeting organically?", "Apps", "Organically"),
        ("First date coffee or first date dinner?", "Coffee", "Dinner"),
        ("Friendship grows fast or slow?", "Fast", "Slow"),
        ("Small gatherings or big parties?", "Small", "Big"),
        ("Host the party or attend the party?", "Host", "Attend"),
        ("Board games at parties or dancing?", "Board games", "Dancing"),
        ("Karaoke yes or karaoke never?", "Yes", "Never"),
        ("Dancing sober or dancing with drinks?", "Sober", "With drinks"),
        ("Night in or night out?", "In", "Out"),
        ("Early nights or late nights?", "Early", "Late"),
        ("Weekend plans or weekend freedom?", "Plans", "Freedom"),
        ("Saturday adventures or Sunday recoveries?", "Saturday", "Sunday"),
        ("Brunch with friends or dinner with friends?", "Brunch", "Dinner"),
        ("Coffee catch-ups or activity catch-ups?", "Coffee", "Activities"),
        ("Buy experiences or buy things?", "Experiences", "Things"),
        ("Quality over quantity always?", "Quality", "Quantity"),
        ("Sustainable products or convenient ones?", "Sustainable", "Convenient"),
        ("Thrift shopping or retail therapy?", "Thrift", "Retail"),
        ("Minimal wallet or maximal wallet?", "Minimal", "Maximal"),
        ("Cash or card daily?", "Cash", "Card"),
        ("Invest early or spend now?", "Invest", "Spend"),
        ("Budget strictly or budget loosely?", "Strictly", "Loosely"),
        ("Save for a house or save for travel?", "House", "Travel"),
        ("Side hustle or free time?", "Side hustle", "Free time"),
        ("Work hard play hard or work calm live calm?", "Hard", "Calm"),
        ("Career first or life first?", "Career", "Life"),
        ("Dream job or dream salary?", "Dream job", "Dream salary"),
        ("Commute short or house big?", "Short commute", "Big house"),
        ("Live downtown or uptown?", "Downtown", "Uptown"),
        ("Big city energy or small town calm?", "Big city", "Small town"),
        ("Walkable neighborhood or drivable?", "Walkable", "Drivable"),
        ("Apartment living or house living?", "Apartment", "House"),
        ("Roommates again or live alone?", "Roommates", "Alone"),
        ("Pet owner or plant parent?", "Pet", "Plant"),
        ("Dog park Saturdays or hiking Saturdays?", "Dog park", "Hiking"),
        ("Volunteer monthly or donate monthly?", "Volunteer", "Donate"),
        ("Learn new skills yearly or master one?", "New yearly", "Master one"),
        ("New Year's resolutions or constant goals?", "Resolutions", "Constant goals"),
        ("Vision board or action plan?", "Vision board", "Action plan"),
        ("Growth mindset or self-acceptance?", "Growth", "Acceptance"),
        ("Therapy or self-help books?", "Therapy", "Books"),
        ("Talk about feelings or process alone?", "Talk", "Alone"),
        ("Stress handled by rest or by action?", "Rest", "Action"),
        ("Perfectionist or good-enough-ist?", "Perfectionist", "Good enough"),
    ],

    "home-living": [
        ("Coffee corner or tea station at home?", "Coffee corner", "Tea station"),
        ("Kitchen island or breakfast nook?", "Island", "Nook"),
        ("Open shelves or closed cabinets?", "Open", "Closed"),
        ("Pantry organized or pantry chaos?", "Organized", "Chaos"),
        ("Fridge magnets or clean fridge door?", "Magnets", "Clean"),
        ("Dishwasher or hand wash?", "Dishwasher", "Hand wash"),
        ("Dishes right away or dishes later?", "Right away", "Later"),
        ("Laundry daily or laundry day?", "Daily", "Laundry day"),
        ("Fold immediately or wrinkle it later?", "Immediately", "Later"),
        ("Ironing: yes or never?", "Yes", "Never"),
        ("Dry cleaning or machine wash everything?", "Dry clean", "Machine wash"),
        ("Closet by color or by season?", "Color", "Season"),
        ("Shoe rack or shoe pile?", "Rack", "Pile"),
        ("Coat hooks or coat closet?", "Hooks", "Closet"),
        ("Living room TV or living room fireplace?", "TV", "Fireplace"),
        ("Couch cushions firm or cloud-soft?", "Firm", "Cloud-soft"),
        ("Sectional or sofa plus armchairs?", "Sectional", "Sofa and chairs"),
        ("Recliner or rocking chair?", "Recliner", "Rocker"),
        ("Coffee table books or coasters only?", "Books", "Coasters"),
        ("Plants in every room or one hardy survivor?", "Every room", "One survivor"),
        ("Fresh flowers weekly or silk flowers?", "Fresh", "Silk"),
        ("Candles or diffusers?", "Candles", "Diffusers"),
        ("Incense or room spray?", "Incense", "Spray"),
        ("Warm lighting or bright lighting?", "Warm", "Bright"),
        ("Lamps everywhere or overhead lights?", "Lamps", "Overhead"),
        ("Dimmers or smart bulbs?", "Dimmers", "Smart bulbs"),
        ("Blackout bedroom or sheer curtains?", "Blackout", "Sheer"),
        ("Bed made daily or bed made never?", "Daily", "Never"),
        ("Bed pillows two or five?", "Two", "Five"),
        ("Weighted blanket or cooling blanket?", "Weighted", "Cooling"),
        ("Memory foam or spring mattress?", "Memory foam", "Spring"),
        ("Bedside lamp or string lights?", "Lamp", "String lights"),
        ("Phone charge bedside or across the room?", "Bedside", "Across the room"),
        ("Morning alarm: radio or tone?", "Radio", "Tone"),
        ("Bathroom: bathtub or walk-in shower?", "Bathtub", "Walk-in"),
        ("Rainfall showerhead or handheld?", "Rainfall", "Handheld"),
        ("Towels white or colorful?", "White", "Colorful"),
        ("Bath mat plush or minimal?", "Plush", "Minimal"),
        ("Bathroom plants or bathroom art?", "Plants", "Art"),
        ("Medicine cabinet or open shelves?", "Cabinet", "Open shelves"),
        ("Home office standing desk or sitting?", "Standing", "Sitting"),
        ("Desk by the window or desk facing the wall?", "Window", "Wall"),
        ("Dual monitors or one big monitor?", "Dual", "One big"),
        ("Laptop on the couch or desk only?", "Couch", "Desk only"),
        ("Home gym corner or gym membership?", "Home corner", "Membership"),
        ("Treadmill in the living room or garage?", "Living room", "Garage"),
        ("Yoga mat always out or stored?", "Always out", "Stored"),
        ("Guest room or home office?", "Guest room", "Home office"),
        ("Guests on an air mattress or sofa bed?", "Air mattress", "Sofa bed"),
        ("Host guests monthly or holidays only?", "Monthly", "Holidays"),
        ("Dinner parties or game nights?", "Dinner parties", "Game nights"),
        ("Formal dining room or open dining space?", "Formal room", "Open space"),
        ("Tablecloth or bare table?", "Tablecloth", "Bare"),
        ("Plates matching or eclectic mix?", "Matching", "Eclectic"),
        ("Fine china kept or used daily?", "Kept", "Daily"),
        ("Silverware polished or dishwasher-safe?", "Polished", "Dishwasher-safe"),
        ("Kitchen herbs on the sill or dried spices?", "Fresh herbs", "Dried"),
        ("Spice rack alphabetized or jumbled?", "Alphabetized", "Jumbled"),
        ("Cast iron or nonstick?", "Cast iron", "Nonstick"),
        ("Knife block or magnetic strip?", "Knife block", "Magnetic strip"),
        ("Stand mixer or hand mixer?", "Stand mixer", "Hand mixer"),
        ("Coffee machine or pour-over setup?", "Machine", "Pour-over"),
        ("Espresso at home or café espresso?", "Home", "Café"),
        ("Fruit bowl on the counter or in the fridge?", "Counter", "Fridge"),
        ("Snack drawer or snack cabinet?", "Drawer", "Cabinet"),
        ("Freezer meals stocked or empty freezer?", "Stocked", "Empty"),
        ("Takeout menus saved or apps only?", "Saved menus", "Apps"),
        ("Groceries delivered or shopped in person?", "Delivered", "In person"),
        ("Farmers market or supermarket?", "Farmers market", "Supermarket"),
        ("Bulk buying or small baskets?", "Bulk", "Small"),
        ("Reusable bags or plastic?", "Reusable", "Plastic"),
        ("Compost bin or trash only?", "Compost", "Trash only"),
        ("Recycling sorted or single stream?", "Sorted", "Single stream"),
        ("Smart thermostat or manual dial?", "Smart", "Manual"),
        ("Voice assistant at home or silence?", "Voice assistant", "Silence"),
        ("Security camera or no cameras?", "Cameras", "None"),
        ("Video doorbell or peephole?", "Video doorbell", "Peephole"),
        ("Robot vacuum or manual vacuum?", "Robot", "Manual"),
        ("Cleaning service or DIY cleaning?", "Service", "DIY"),
        ("Weekend cleaning blitz or daily tidy?", "Blitz", "Daily tidy"),
        ("Storage unit or declutter everything?", "Storage unit", "Declutter"),
        ("Garage or street parking?", "Garage", "Street"),
        ("Yard manicured or wild?", "Manicured", "Wild"),
        ("Lawn or wildflower meadow?", "Lawn", "Meadow"),
        ("Vegetable garden or flower garden?", "Vegetables", "Flowers"),
        ("Hammock or porch swing?", "Hammock", "Porch swing"),
        ("Fire pit or water feature?", "Fire pit", "Water feature"),
        ("Outdoor grill or outdoor kitchen?", "Grill", "Outdoor kitchen"),
        ("Balcony garden or balcony lounge?", "Garden", "Lounge"),
        ("Christmas decorations minimal or maximal?", "Minimal", "Maximal"),
        ("Holiday lights white or multicolor?", "White", "Multicolor"),
        ("Real Christmas tree or artificial?", "Real", "Artificial"),
        ("Halloween decorated or undecorated?", "Decorated", "Undecorated"),
        ("Home scent: linen or vanilla?", "Linen", "Vanilla"),
        ("Walls with art or walls bare?", "Art", "Bare"),
        ("Gallery wall or one big statement piece?", "Gallery wall", "Statement piece"),
        ("Paint colors bold or neutral?", "Bold", "Neutral"),
        ("Accent wall or all one color?", "Accent wall", "One color"),
        ("Wood floors or carpet?", "Wood", "Carpet"),
        ("Rugs layered or bare floors?", "Layered rugs", "Bare"),
        ("Wallpaper or paint?", "Wallpaper", "Paint"),
        ("Family photos displayed or in albums?", "Displayed", "Albums"),
    ],
}
