"""Seed questions: question_seed_couples.
Format: {category_id: [(prompt, option1, option2), ...]}
"""

SEED = {
    "couples": [
        ('Good morning text or good night text?', 'Good morning', 'Good night'),
        ('Forehead kiss or kiss that makes you late?', 'Forehead kiss', 'The late one'),
        ('Fall asleep entangled or just touching hands?', 'Entangled', 'Touching hands'),
        ('Kiss hello before anything is said or talk first, kiss later?', 'Kiss first', 'Talk first'),
        ('Hold hands walking or walk arm in arm?', 'Hold hands', 'Arm in arm'),
        ('Love letters or love said out loud, unprompted?', 'Letters', 'Said out loud'),
        ('Pet names in private or pet names in public?', 'Private only', 'Public too'),
        ('Surprise flowers or flowers with a reason attached?', 'Surprise', 'With a reason'),
        ('Slow dance in the kitchen or dance until the bar closes?', 'Kitchen', 'Bar closes'),
        ("Anniversary trip or a letter you'll keep forever?", 'Trip', 'Letter'),
        ("A kiss on the forehead when you're stressed or ten minutes of listening?", 'Forehead kiss', 'Ten minutes'),
        ('Goodbye kiss at the door or the text when you land?', 'At the door', 'When I land'),
        ('Be complimented in front of others or in the dark at home?', 'In front of others', 'In the dark'),
        ('Morning cuddle that delays everything or coffee made for you?', 'Cuddle', 'Coffee made'),
        ('Date night dressed up or dressed down?', 'Dressed up', 'Dressed down'),
        ('After a fight: repair right away or sleep on it?', 'Repair right away', 'Sleep on it'),
        ('Silent treatment or say it straight?', 'Silent treatment', 'Say it straight'),
        ('Fight loud and fast or quiet and long?', 'Loud and fast', 'Quiet and long'),
        ('Apologize first or forgive first?', 'Apologize first', 'Forgive first'),
        ('An apology in words or an apology in actions?', 'In words', 'In actions'),
        ("When you're wrong: admit it instantly or sit with it first?", 'Admit instantly', 'Sit with it'),
        ('Keep the fight about today or name the old wound underneath?', 'Today only', 'Name the wound'),
        ('Argue over text or wait to argue in person?', 'Over text', 'In person'),
        ('Win the argument or fix the problem?', 'Win', 'Fix it'),
        ('Cool off alone or cool off sitting together in silence?', 'Alone', 'Together, silent'),
        ('A fight that ends in laughter or a fight that ends in a plan?', 'Laughter', 'A plan'),
        ('Harsh truth now or gentle truth spread over time?', 'Harsh now', 'Gentle over time'),
        ("Say 'you hurt me' or hope they figure it out?", 'Say it', 'Hope they see it'),
        ('A pause word for hard talks or push through to the end?', 'Pause word', 'Push through'),
        ("Ask 'are we okay?' or act like nothing happened?", 'Ask', 'Act normal'),
        ('Repair with touch or repair with words?', 'Touch', 'Words'),
        ('Phone passwords shared or privacy kept?', 'Shared', 'Privacy kept'),
        ("A partner's ex as a friend: fine or never?", 'Fine', 'Never'),
        ('When jealousy shows up: name it or swallow it?', 'Name it', 'Swallow it'),
        ('Someone flirts with your partner: laugh it off or mark your territory?', 'Laugh it off', 'Mark territory'),
        ('Trust completely until proven otherwise or verify first?', 'Trust first', 'Verify first'),
        ('A secret that protects or a truth that stings?', 'Protect', 'Sting'),
        ('Be honest about finding others attractive or keep that private?', 'Be honest', 'Keep it private'),
        ('Their friend flirts with you: tell them or shut it down yourself?', 'Tell them', 'Handle it'),
        ('Ask how they really feel or wait to be told?', 'Ask', 'Wait'),
        ("A night out you'd narrate in full or summarize in one line?", 'Full narration', 'One line'),
        ('If they cheated emotionally: work on it or walk away?', 'Work on it', 'Walk away'),
        ('Being trusted completely or being chosen daily?', 'Trusted', 'Chosen'),
        ('Phones at dinner: face down or in another room?', 'Face down', 'Another room'),
        ('One hour of full attention or a whole evening of half-attention?', 'One full hour', 'Half all night'),
        ('Scrolling in bed together or reading in bed together?', 'Scrolling', 'Reading'),
        ('Listen to fix or listen to understand?', 'To fix', 'To understand'),
        ('Remember the small details or the big moments?', 'Small details', 'Big moments'),
        ('Be heard or be held?', 'Heard', 'Held'),
        ('A partner who listens or a partner who makes you laugh?', 'Listens', 'Makes you laugh'),
        ('A merged life or two lives that overlap often?', 'Merged', 'Overlapping'),
        ('Solo trips or never travel apart?', 'Solo trips', 'Never apart'),
        ('Lovers first or best friends first?', 'Lovers first', 'Best friends first'),
        ('Space to miss each other or closeness that never breaks?', 'Space to miss', 'Never break'),
        ('Text all day or save it all for tonight?', 'Text all day', 'Save it for tonight'),
        ('Shared hobbies or separate passions you respect?', 'Shared hobbies', 'Separate passions'),
        ('A weekend apart to recharge or together to reconnect?', 'Apart', 'Together'),
        ('Tell each other everything or keep an inner room private?', 'Everything', 'An inner room'),
        ('Grow into one person or grow side by side?', 'Into one', 'Side by side'),
        ('Miss them quietly or tell them you miss them?', 'Quietly', 'Tell them'),
        ('Do everything as a team or divide and conquer?', 'Always together', 'Divide and conquer'),
        ('Introvert weekends at home or out in the world together?', 'Home', 'Out in the world'),
        ('Lights on or candlelight?', 'Lights on', 'Candlelight'),
        ('Slow and deliberate or playful and teasing?', 'Slow', 'Teasing'),
        ('A kiss that lingers or a look that does?', 'The kiss', 'The look'),
        ('Initiate or be pursued?', 'Initiate', 'Be pursued'),
        ('Morning intimacy or midnight intimacy?', 'Morning', 'Midnight'),
        ('Spontaneous desire or anticipation you build for days?', 'Spontaneous', 'Built for days'),
        ('Say what you want or let them discover it?', 'Say it', 'Let them discover'),
        ('New lingerie or their old shirt?', 'Lingerie', 'The old shirt'),
        ('Dancing close in the kitchen or closer behind a closed door?', 'Kitchen', 'Closed door'),
        ('A weekend in bed or a weekend away?', 'In bed', 'Away'),
        ('The buildup or the afterglow?', 'The buildup', 'The afterglow'),
        ('Share a shy fantasy or keep it yours?', 'Share it', 'Keep it mine'),
        ('Desire that simmers for days or surprises you at once?', 'Simmers', 'Surprises'),
        ('A touch in passing or a touch with intent?', 'In passing', 'With intent'),
        ('Kiss in the rain or kiss against a wall?', 'In the rain', 'Against a wall'),
        ("Flirt like it's the first time or flirt like it's forever?", 'First time', 'Forever'),
        ('Joint account or yours, mine, and ours?', 'Joint', 'Yours/mine/ours'),
        ('Splurge on each other or save for a shared dream?', 'Splurge', 'Save together'),
        ("Know each other's exact salaries or keep that private?", 'Know', 'Private'),
        ('Money fights: about the numbers or about the control?', 'The numbers', 'The control'),
        ('An expensive gift or an expensive experience?', 'Gift', 'Experience'),
        ('One of you budgets or both of you do?', 'One budgets', 'Both budget'),
        ('Lend your partner money or gift it and forget it?', 'Lend', 'Gift and forget'),
        ('Their family visits monthly or twice a year?', 'Monthly', 'Twice a year'),
        ('Tell your family everything or keep us between us?', 'Everything', 'Between us'),
        ('Holidays with your family or theirs?', 'Mine', 'Theirs'),
        ('Always defend your partner to your family or pick your battles?', 'Always', 'Pick battles'),
        ('A friend disrespects your partner: cut them off or call it out?', 'Cut them off', 'Call it out'),
        ('Merge your friend groups or keep separate circles?', 'Merge', 'Separate circles'),
        ('Speak well of your partner in their absence or tease them?', 'Speak well', 'Tease'),
        ('Post each other online or keep the evidence private?', 'Post', 'Private'),
        ("When they're drowning: fix it or sit in it with them?", 'Fix it', 'Sit in it'),
        ('Cheerleader or honest critic?', 'Cheerleader', 'Honest critic'),
        ("Carry them when they can't or push them when they won't?", 'Carry', 'Push'),
        ('Celebrate the small wins or save it for the big ones?', 'Small wins', 'Big ones'),
        ('When they cry: hold them or give them air?', 'Hold them', 'Give them air'),
        ('Sick days: nurse them or order soup and vanish?', 'Nurse them', 'Soup and space'),
        ('Their bad week: plan an escape or a quiet night in?', 'Escape', 'Quiet night in'),
        ('Be their emergency contact or their first phone call?', 'Emergency contact', 'First phone call'),
        ('Believe in them out loud or quietly take up slack?', 'Out loud', 'Take up slack'),
        ('Calm them down or get angry on their behalf?', 'Calm them', 'Get angry for them'),
        ('Being truly known or being truly adored?', 'Known', 'Adored'),
        ('A love that calms you or one that sets you on fire?', 'Calms', 'Sets you on fire'),
        ('Comfortable silence or conversation until 3 a.m.?', 'Silence', 'Until 3 a.m.'),
        ("Stay because it's good or because it's comfortable?", "Because it's good", "Because it's easy"),
        ('The person who challenges you or the one who steadies you?', 'Challenges', 'Steadies'),
        ('Falling in love or being in love?', 'Falling', 'Being in'),
        ('Would you choose them again, knowing everything?', 'Yes, again', "I'd hesitate"),
        ('A partner who needs you or one who wants you?', 'Needs me', 'Wants me'),
        ("Their happiness or the relationship's fairness?", 'Their happiness', 'Fairness'),
        ("Say 'I need you' or power through alone?", 'Say it', 'Power through'),
        ('Love as a feeling or love as a decision?', 'A feeling', 'A decision'),
        ('Be their soft place or their safe honest voice?', 'Soft place', 'Honest voice'),
        ('Routine that soothes or novelty that scares?', 'Routine', 'Novelty'),
        ('Their hand on your back or your name in their mouth?', 'On my back', 'In their mouth'),
        ('Grow old gently together or burn bright and risk the fall?', 'Grow old gently', 'Burn bright'),
        ('The love you chase or the love that stays?', 'The chase', 'The one that stays'),
        ('Reunions at the airport or reunions at the front door?', 'Airport', 'Front door'),
        ("An old photo of us or a memory we haven't made yet?", 'Old photo', 'One not yet made'),
        ('Their heartbeat or their breathing to fall asleep to?', 'Heartbeat', 'Breathing'),
        ('One blanket or two?', 'One', 'Two'),
        ('A nickname only they use or your real name said softly?', 'The nickname', 'My name, softly'),
        ('Their hoodie that smells like them or their side of the bed?', 'The hoodie', 'Their side'),
        ('Forgiveness quick or slowly earned?', 'Quick', 'Earned slowly'),
        ('Make up mid-argument or after the storm passes?', 'Mid-argument', 'After the storm'),
        ('A vow renewed every year or one promise kept forever?', 'Renewed yearly', 'Kept forever'),
        ('Them reading your journal or your search history?', 'Journal', 'Search history'),
        ('Their ex at the wedding: invited or not?', 'Invited', 'Not'),
        ('Dance with them at every wedding or keep the table and talk?', 'Every dance', 'The table'),
        ('A toast that makes you cry or one that makes you laugh?', 'Cry', 'Laugh'),
        ('Cry in front of them or only in the shower?', 'In front of them', 'In the shower'),
        ('Learn their love language or teach them yours?', 'Learn theirs', 'Teach mine'),
        ('Surprise them on their birthday or build the day together?', 'Surprise them', 'Build together'),
        ('A shared bucket list or surprise solo plans?', 'Shared list', 'Solo surprises'),
        ('Their success outshining yours: celebrate or quietly struggle?', 'Celebrate', 'Quietly struggle'),
        ('Compete with each other or never keep score?', 'Compete', 'No score'),
        ('Their stress: take it personally or take it seriously?', 'Personally', 'Seriously'),
        ('Bring them coffee unasked or a back rub unasked?', 'Coffee', 'Back rub'),
        ("A playlist that's 'ours' or headphones side by side?", 'Ours', 'Side by side'),
        ('Photos of us everywhere or a few kept private?', 'Everywhere', 'A few, private'),
        ("Meet each other's exes or leave the past in the past?", 'Meet them', 'Leave it'),
        ('Talk about us in therapy or at the kitchen table?', 'Therapy', 'Kitchen table'),
        ('A silly fight that ends in laughter or a real one that ends in tears?', 'Laughter', 'Tears'),
        ("Hear 'I'm proud of you' or 'I believe in you'?", 'Proud of you', 'Believe in you'),
        ('Be missed or be needed?', 'Missed', 'Needed'),
        ('Their happiness without you or their struggle with you?', 'Happy without me', 'Struggling with me'),
        ('Move cities for them or ask them to stay?', 'I move', 'They stay'),
        ("A small wedding that's intimate or a big party for everyone?", 'Small', 'Big party'),
        ('Grow old in one town or grow old trying new places?', 'One town', 'New places'),
        ("Their hand at the doctor's office or their voice on the phone?", 'Their hand', 'Their voice'),
        ('Learn to love what they love or keep your worlds separate?', 'Learn to love it', 'Separate worlds'),
        ("Be each other's emergency or each other's everyday?", 'Emergency', 'Everyday'),
        ("Sense when something's wrong or be told outright?", 'Sense it', 'Be told'),
        ('A love documented in letters or retold as stories?', 'Letters', 'Stories'),
        ('The kitchen at midnight talking or the bed at midnight not talking?', 'Kitchen', 'Bed'),
        ("Kiss before we leave or the second we're home?", 'Before we leave', "Second we're home"),
        ('Their anger: meet it with calm or match it?', 'Calm', 'Match it'),
    ],
    "date-night": [
        ('A date that ends at breakfast or one you replay for weeks?', 'Ends at breakfast', 'Replay for weeks'),
        ('Planned date nights or ones that happen by accident?', 'Planned', 'By accident'),
        ("Try the new place or return to 'our' place?", 'The new place', 'Our place'),
        ('Dinner you dress up for or street food you eat walking?', 'Dressed up', 'Street food'),
        ('A quiet table in the corner or seats at the bar?', 'Corner table', 'At the bar'),
        ('Tasting menu with wine pairings or one perfect dish?', 'Tasting menu', 'One perfect dish'),
        ('Fine dining or a hole-in-the-wall only locals know?', 'Fine dining', 'Hole-in-the-wall'),
        ('Split the bill or take turns treating?', 'Split', 'Take turns'),
        ('Book the reservation or wing it and see?', 'Book it', 'Wing it'),
        ('Double date or table for two?', 'Double date', 'Table for two'),
        ('A date that starts at noon or one that starts at midnight?', 'Noon', 'Midnight'),
        ('End the night with dessert or with a walk?', 'Dessert', 'A walk'),
        ("Know exactly where you're going or follow the night?", 'Know the plan', 'Follow the night'),
        ('A first-date energy night or an old-married-comfort night?', 'First-date energy', 'Old-comfort'),
        ('Takeout on the couch or cooked together in the kitchen?', 'Takeout', 'Cooked together'),
        ('A long dinner with wine or a short one with somewhere to be?', 'Long, slow', 'Somewhere to be'),
        ('Live jazz in a small club or a DJ until 4 a.m.?', 'Live jazz', 'DJ till 4'),
        ('Theatre on opening night or cinema in the back row?', 'Theatre', 'Back-row cinema'),
        ('An art gallery where you whisper or a rooftop where you shout?', 'Gallery', 'Rooftop'),
        ('Sunset sail or night drive with no destination?', 'Sunset sail', 'Night drive'),
        ('Wine tasting or whiskey, neat?', 'Wine', 'Whiskey'),
        ('A casino night or a board-game night?', 'Casino', 'Board games'),
        ('Karaoke done badly or dancing done well?', 'Karaoke badly', 'Dancing well'),
        ('A walk through the city at night or a hike at dawn?', 'City at night', 'Hike at dawn'),
        ('Stargazing on a roof or people-watching at a café?', 'Stargazing', 'People-watching'),
        ('A spa day together or a city break apart-but-together?', 'Spa day', 'City break'),
        ('Dance even though nobody else is dancing or watch them dance?', 'Dance', 'Watch'),
        ('A rooftop bar with a view or a basement bar with a secret?', 'Rooftop', 'Basement'),
        ('Fireworks or firepit?', 'Fireworks', 'Firepit'),
        ('A night market abroad or a farmers market at home?', 'Night market', 'Farmers market'),
        ('Camp under real stars or a hotel with too many pillows?', 'Camp', 'Hotel'),
        ('A museum after dark or a fairground after hours?', 'Museum', 'Fairground'),
        ("Ask the question you're afraid of or keep it light?", 'Ask it', 'Keep it light'),
        ('Talk about your dreams or your doubts?', 'Dreams', 'Doubts'),
        ("Their hand on your thigh under the table or eyes that don't leave yours?", 'Hand', 'Eyes'),
        ("Flirt across a crowded room or into each other's ear?", 'Across the room', 'In their ear'),
        ('A conversation about the future or about the past?', 'Future', 'Past'),
        ("Tell them something you've never told anyone or hear their secret?", 'Tell mine', 'Hear theirs'),
        ('Slow dance even with no dance floor?', 'Yes', 'Only with a floor'),
        ('Make the first move or let the tension build?', 'First move', 'Let it build'),
        ('Order for each other or keep it to yourselves?', 'Order for them', 'My own order'),
        ('A question game that goes deep or silence that says more?', 'Question game', 'The silence'),
        ('Laugh until you cry or talk until the staff stack the chairs?', 'Laugh', 'Talk'),
        ('Get ready together or meet there and see each other fresh?', 'Ready together', 'Meet there'),
        ('A photograph of the night or just the memory?', 'Photograph', 'Memory'),
        ('Their jacket on your shoulders or their arm around them anyway?', 'The jacket', 'The arm'),
        ('An inside joke by the end of the night or a plan for the next one?', 'Inside joke', 'Next plan'),
        ('Be surprised completely or co-design the night?', 'Surprised', 'Co-designed'),
        ("A goodnight kiss at the door or 'come up for one more'?", 'At the door', 'One more'),
        ("Walk me home or call me when you're home?", 'Walk me', 'Call me'),
        ('A night that ends in a taxi together or walking separately?', 'Taxi together', 'Separately'),
        ('Sleep in on Sunday or brunch reservations at 11?', 'Sleep in', 'Brunch at 11'),
        ('The night ends at the party or continues at home?', 'The party', 'At home'),
        ("A kiss goodnight you mean or one you've waited all night for?", 'One you mean', 'One you waited for'),
        ('Fall asleep mid-movie or pause it and go to bed properly?', 'Mid-movie', 'Pause it'),
        ('A weekend morning that starts slow or starts with coffee outside?', 'Slow', 'Coffee outside'),
        ('Plan the whole night or be completely surprised?', 'I plan', 'Surprise me'),
        ('Dress to impress them or dress for yourself?', 'For them', 'For myself'),
        ('A partner who plans or one who shows up beautifully?', 'Plans', 'Shows up'),
        ('Try hard on anniversaries or on random Tuesdays?', 'Anniversaries', 'Random Tuesdays'),
        ('The effort of getting ready or the moment you walk in?', 'Getting ready', 'Walking in'),
        ('New lingerie or new perfume?', 'Lingerie', 'Perfume'),
        ("Heels that hurt or flats that don't?", 'Heels', 'Flats'),
        ('Their cologne on your collar or yours on their pillow?', 'On my collar', 'On their pillow'),
        ('A date where you lose track of time or one with a perfect view?', 'Lose track of time', 'Perfect view'),
        ('Rainy-night date or golden-hour one?', 'Rain', 'Golden hour'),
        ('City lights or candlelight?', 'City lights', 'Candlelight'),
        ('A first date all over again or a twentieth anniversary dinner?', 'First date', 'Twentieth'),
        ('Stay for one more drink or leave wanting more?', 'One more', 'Leave wanting'),
        ('The restaurant that never rushes you or the one that remembers you?', 'Never rushes', 'Remembers us'),
        ('Dessert first or dessert last?', 'First', 'Last'),
        ('A shared dessert or two separate ones, no negotiating?', 'Shared', 'Separate'),
        ('Be asked out properly or ask them yourself?', 'Be asked', 'Ask them'),
        ('A note slipped across the table or a whisper in the hallway?', 'The note', 'The whisper'),
        ('Hold the gaze or look away smiling?', 'Hold it', 'Look away'),
        ("Dance close where it's crowded or alone where it's empty?", "Where it's crowded", "Where it's empty"),
        ('The proposal you plan together or the one that blindsides you?', 'Planned together', 'Blindsided'),
        ('Their eyes across a party or their hand in a car park?', 'Across a party', 'In a car park'),
        ('A slow song you both know or a new one neither of you does?', 'One we know', "One we don't"),
        ("The night you'll remember or the morning you'll talk about?", 'The night', 'The morning'),
        ('Watch the sunrise together or finally sleep?', 'Sunrise', 'Sleep'),
        ("A goodbye that's brief or one that keeps starting over?", 'Brief', 'Starting over'),
        ('Home before midnight or watch the city wake up?', 'Before midnight', 'Watch it wake'),
        ('The last dance or the first one?', 'Last', 'First'),
        ('A picnic in the park or a penthouse bar?', 'Picnic', 'Penthouse bar'),
        ('Watch them get ready or be watched?', 'Watch them', 'Be watched'),
        ('A date that requires a passport or one that needs no shoes?', 'Passport', 'No shoes'),
        ('Cook together in silence or with the music too loud?', 'In silence', 'Music too loud'),
        ('Feed each other in public or keep hands to yourselves?', 'Feed them', 'Hands to myself'),
        ('A bar with a hidden entrance or a restaurant with no sign?', 'Hidden bar', 'No sign'),
        ('Kiss at the top of the Ferris wheel or under the fireworks?', 'Ferris wheel', 'Fireworks'),
        ('On a date: quality time or physical touch?', 'Quality time', 'Physical touch'),
        ('A bucket-list restaurant or a bench with great takeaway?', 'Bucket list', 'The bench'),
        ('Stay in the city or drive until you find something?', 'Stay', 'Drive till we do'),
        ('Their playlist or yours on the way there?', 'Theirs', 'Mine'),
        ('Take one perfect photo or stay in the moment?', 'The photo', 'The moment'),
        ('Learn to dance properly or laugh at trying?', 'Learn properly', 'Laugh at trying'),
        ('A hotel in your own city or a borrowed beach house?', 'Hotel in town', 'Beach house'),
        ('Book the last table or take the long walk first?', 'Last table', 'The walk'),
        ('Coffee first or straight to dinner?', 'Coffee first', 'Straight to dinner'),
    ],
    "deep-talks": [
        ('Regret the things you did or the things you never tried?', 'Did', 'Never tried'),
        ('One chance to redo a decision or one to see the road not taken?', 'Redo it', 'See the other road'),
        ('Live without regrets or learn to live with them?', 'Without', 'With them'),
        ("The safe choice you made or the risk you didn't?", 'The safe choice', 'The risk'),
        ('Fail publicly or succeed privately?', 'Fail publicly', 'Succeed privately'),
        ("Do it scared or wait until you're ready?", 'Do it scared', 'Wait for ready'),
        ('A life carefully planned or one that surprised you?', 'Planned', 'Surprised'),
        ('Burn the boats or keep an exit open?', 'Burn them', 'Keep the exit'),
        ('Say the hard thing or carry the unsaid?', 'Say it', 'Carry it'),
        ("The apology you owe or the one you're owed?", 'The one I owe', "The one I'm owed"),
        ('Which is scarier: being forgotten or being watched?', 'Forgotten', 'Watched'),
        ('Which is scarier: failing or never wanting anything?', 'Failing', 'Wanting nothing'),
        ('Which is scarier: dying young or living small?', 'Dying young', 'Living small'),
        ('Which is scarier: the truth or the not-knowing?', 'The truth', 'Not knowing'),
        ('Which is scarier: being alone or being known completely?', 'Alone', 'Known completely'),
        ('Which is scarier: change or stagnation?', 'Change', 'Stagnation'),
        ('Courage that acts or courage that endures?', 'Acts', 'Endures'),
        ('Face the fear once or manage it forever?', 'Once', 'Forever'),
        ("The fear you've beaten or the one you've made peace with?", 'Beaten', 'Made peace with'),
        ('Ask for help or figure it out alone?', 'Ask', 'Alone'),
        ('Know when your time comes or how it comes?', 'When', 'How'),
        ('Ten perfect years or forty okay ones?', 'Ten perfect', 'Forty okay'),
        ('Live forever or live fully?', 'Forever', 'Fully'),
        ('More time or more energy?', 'Time', 'Energy'),
        ('Grow old or stay young at heart but age anyway?', 'Grow old gracefully', 'Fight it'),
        ("The past you miss or the future you're unsure of?", 'The past', 'The future'),
        ('If you had one year left: travel or stay with everyone you love?', 'Travel', 'Stay'),
        ('Be remembered for what you built or who you were?', 'What I built', 'Who I was'),
        ('Your eulogy written by strangers or by the people who knew you?', 'Strangers', 'Who knew me'),
        ('Time moving faster as you age: fight it or savor it?', 'Fight it', 'Savor it'),
        ('Spend your last dollar on a memory or leave it behind?', 'The memory', 'Leave it'),
        ('A shorter life you chose or a longer one that happened to you?', 'Chose', 'Happened to me'),
        ('Love that changes you or love that lets you stay yourself?', 'Changes me', 'Lets me be me'),
        ('To be loved or to be understood?', 'Loved', 'Understood'),
        ('A love that saves you or one that stands beside you?', 'Saves me', 'Stands beside'),
        ('Loving someone or being lovable?', 'Loving', 'Being lovable'),
        ("The love you grew up seeing or the love you're building?", 'Grew up with', 'Building now'),
        ('Love at first sight or love that sneaks up over years?', 'First sight', 'Over years'),
        ("A heart that's guarded or one that's been broken open?", 'Guarded', 'Broken open'),
        ('Stay friends with an ex or let the past close its door?', 'Stay friends', 'Close the door'),
        ('Grief for people or grief for versions of yourself?', 'For people', 'For who I was'),
        ("Say 'I love you' first or wait to hear it?", 'Say it first', 'Wait to hear it'),
        ('The self you show the world or the one at 3 a.m.?', "The world's version", 'The 3 a.m. one'),
        ("Like who you've become or who you were?", 'Became', 'Was'),
        ("Be your own hero or someone else's?", 'My own', "Someone else's"),
        ('Define yourself by your wins or your scars?', 'Wins', 'Scars'),
        ('The opinion strangers hold of you or the one you hold of yourself?', "Strangers'", 'My own'),
        ('Reinvent yourself or deepen who you are?', 'Reinvent', 'Deepen'),
        ("Who you are when nobody's watching: proud or worried?", 'Proud', 'Worried'),
        ('Growth that hurts or comfort that numbs?', 'Hurts', 'Numbs'),
        ('Your worst habit: change it or claim it?', 'Change it', 'Claim it'),
        ('Be the person your younger self needed or the one your future self wants?', 'Past me needed', 'Future me wants'),
        ('Rich in money or rich in time?', 'Money', 'Time'),
        ('Work you love or work that leaves you free?', 'Love', 'Frees me'),
        ('Ambition that costs you or contentment that caps you?', 'Ambition', 'Contentment'),
        ('Retire early and simply or late and lavishly?', 'Early, simple', 'Late, lavish'),
        ("The career you'd choose at 15 or the one you'd choose now?", 'At 15', 'Now'),
        ("Success measured by money or by mornings you don't dread?", 'Money', 'Mornings'),
        ('A title that impresses or work that matters?', 'Title', 'Matters'),
        ('Hustle now, rest later or balance it all along?', 'Hustle now', 'Balance'),
        ('Would you take a pay cut to love your work?', 'Yes', 'No'),
        ('Money buys freedom or money buys safety?', 'Freedom', 'Safety'),
        ('The dream you chase or the one you protect?', 'Chase', 'Protect'),
        ('Burn out for the dream or pace yourself and maybe miss it?', 'Burn out', 'Pace myself'),
        ('Honesty that wounds or kindness that lies?', 'Wounding truth', 'Lying kindness'),
        ('A truth about you no one knows or one everyone suspects?', 'No one knows', 'Everyone suspects'),
        ('Be exposed completely or misread forever?', 'Exposed', 'Misread'),
        ("Keep someone's secret or protect someone's feelings?", 'The secret', 'The feelings'),
        ('White lies that grease life or radical honesty that grates?', 'White lies', 'Radical honesty'),
        ('Confess something old or let it die with the past?', 'Confess', 'Let it die'),
        ('Be the person who asks hard questions or who answers them?', 'Asks', 'Answers'),
        ('Forgive yourself or forgive them first?', 'Myself', 'Them'),
        ('Forgive and remember or forget and move on?', 'Remember', 'Forget'),
        ('An apology you need or closure you can give yourself?', 'The apology', 'Self-closure'),
        ('Hold the grudge or drop it and stay guarded?', 'Hold it', 'Drop it'),
        ('Reconcile with the person or with the memory?', 'The person', 'The memory'),
        ('The friend who wronged you: reach out or let them?', 'Reach out', 'Let them'),
        ('Meaning is found or made?', 'Found', 'Made'),
        ('Everything happens for a reason or we make the reasons?', 'For a reason', 'We make them'),
        ('Faith that comforts or doubt that questions?', 'Faith', 'Doubt'),
        ("A universe with a plan or one that's indifferent?", 'A plan', 'Indifferent'),
        ('Something after this or just this?', 'Something after', 'Just this'),
        ('Suffering that teaches or suffering that just hurts?', 'Teaches', 'Just hurts'),
        ('Fate or choices?', 'Fate', 'Choices'),
        ('Happiness as a goal or a byproduct?', 'A goal', 'A byproduct'),
        ('Wisdom from books or from scars?', 'Books', 'Scars'),
        ('A life of comfort or a life of meaning?', 'Comfort', 'Meaning'),
        ('Lonely in a crowd or lonely at home?', 'In a crowd', 'At home'),
        ('Many acquaintances or one true friend?', 'Many', 'One true'),
        ('Be understood by everyone or truly known by one?', 'By everyone', 'By one'),
        ("Connection that's deep but rare or light but constant?", 'Deep, rare', 'Light, constant'),
        ('Small talk or comfortable silence?', 'Small talk', 'Silence'),
        ('The friend you call in crisis or the one you call with good news?', 'In crisis', 'With good news'),
        ('Missing people or being missed?', 'Missing them', 'Being missed'),
        ('Outgrow people or grow apart politely?', 'Outgrow', 'Grow apart'),
        ('The family you were born into or the one you choose?', 'Born into', 'Choose'),
        ("Your parents' approval or your own peace?", 'Approval', 'My peace'),
        ('The trait you inherited or the one you swore to break?', 'Inherited', 'Swore to break'),
        ('Raise kids the way you were raised or the opposite?', 'Same', 'Opposite'),
        ('Your parents getting older: prepare or avoid thinking?', 'Prepare', 'Avoid'),
        ('Family duty or personal truth?', 'Duty', 'Truth'),
        ('The family recipe or the family story?', 'Recipe', 'Story'),
        ('Be desired or be admired?', 'Desired', 'Admired'),
        ('Beauty that fades or wisdom that grows?', 'Beauty', 'Wisdom'),
        ('Aging: melancholy or privilege?', 'Melancholy', 'Privilege'),
        ('Look good or feel good?', 'Look good', 'Feel good'),
        ('Youth wasted on the young or wisdom wasted on the old?', 'On the young', 'On the old'),
        ('Be the most interesting person in the room or the kindest?', 'Interesting', 'Kindest'),
        ('Roots or wings?', 'Roots', 'Wings'),
        ('One home forever or a new city every few years?', 'One home', 'New cities'),
        ("Where you're from or where you're going?", 'From', 'Going'),
        ('Belong somewhere or belong to someone?', 'Somewhere', 'Someone'),
        ('Return to the place you grew up or never look back?', 'Return', 'Never look back'),
        ('Home is a place or a person?', 'A place', 'A person'),
        ('Your ceiling or your floor — which defines you?', 'Ceiling', 'Floor'),
        ("What you'd do with a free year or what you'd do with a last one?", 'Free year', 'Last year'),
        ('The version of you that dreams biggest or sleeps best?', 'Dreams biggest', 'Sleeps best'),
        ('Control your life or trust it?', 'Control', 'Trust'),
        ('Becoming or arriving?', 'Becoming', 'Arriving'),
        ("A truth you've made peace with or one you're still fighting?", 'Made peace', 'Still fighting'),
        ("The door that closed or the one that hasn't opened yet?", 'Closed', 'Not yet open'),
        ('Envy as information or as poison?', 'Information', 'Poison'),
        ('Your five-year plan or your wild card?', 'The plan', 'The wild card'),
        ("What you'd tell your younger self or what you'd ask your older self?", 'Tell younger', 'Ask older'),
        ('Answer the big questions or learn to live inside them?', 'Answer them', 'Live inside them'),
        ("The moment you're proudest of or the one you're most ashamed of?", 'Proudest', 'Most ashamed'),
        ('Who you are in a crisis or who you are on a lazy Sunday?', 'In a crisis', 'Lazy Sunday'),
        ('Your word kept at a cost or a promise broken for a reason?', 'Kept at cost', 'Broken'),
        ('Know exactly how others see you or not at all?', 'Know exactly', 'Not at all'),
        ('Character in the dark or reputation in the light?', 'In the dark', 'In the light'),
        ('Their expectations of you or your expectations of yourself?', 'Theirs', 'My own'),
        ('Trust your head or your gut?', 'Head', 'Gut'),
        ('Old friends who knew you then or new ones who know you now?', 'Knew me then', 'Know me now'),
        ('Being the strong one or being allowed to fall apart?', 'The strong one', 'Fall apart'),
        ("Ask 'what if' or ask 'what now'?", 'What if', 'What now'),
        ('Dream out loud or keep it safe and unspoken?', 'Out loud', 'Unspoken'),
        ('The mistake that taught you or the one that still costs you?', 'Taught me', 'Still costs'),
        ('Vulnerability as strength or as risk?', 'Strength', 'Risk'),
        ('Would you rather your child be brilliant or kind?', 'Brilliant', 'Kind'),
        ('A life well-lived or a life well-loved?', 'Well-lived', 'Well-loved'),
        ('Do something differently or do it all again exactly?', 'Differently', 'Exactly the same'),
        ("What's scarier: too many options or none?", 'Too many', 'None'),
        ('Boredom or chaos?', 'Boredom', 'Chaos'),
        ("A conversation you'd redo or one you never got to have?", 'Redo one', 'Never had'),
        ('Closure or continuation?', 'Closure', 'Continuation'),
        ('Talk about death openly or barely at all?', 'Openly', 'Barely'),
        ("The compliment you remember or the insult you can't forget?", 'The compliment', 'The insult'),
        ('The person you were at 20: cringe or credit?', 'Cringe', 'Credit'),
        ('Nostalgia as comfort or as trap?', 'Comfort', 'Trap'),
        ('The risk you took or the one waiting on your list?', 'The one I took', 'The one waiting'),
    ],
    "future-us": [
        ("The life you're building: farmhouse or penthouse?", 'Farmhouse', 'Penthouse'),
        ('Grow roots in one city or follow the work wherever it goes?', 'Roots', 'Follow the work'),
        ("A big life that's uncertain or a small one that's secure?", 'Big, uncertain', 'Small, secure'),
        ('Dream out loud together or protect each other from jinxes?', 'Out loud', "Don't jinx it"),
        ('A five-year plan or an open road?', 'The plan', 'The open road'),
        ('Someday rich or someday free?', 'Rich', 'Free'),
        ('Take the sabbatical year or the promotion?', 'Sabbatical', 'Promotion'),
        ("A quiet life you love or a loud one you're proud of?", 'Quiet', 'Loud'),
        ('One career for life or a new one every decade?', 'One', 'New each decade'),
        ('Live abroad for a year or invest that money in a home?', 'Abroad', 'The home'),
        ('Rent in the city you love or buy where you can afford?', 'Rent, love it', 'Buy, afford it'),
        ('Would you start a business together or never mix money and love?', 'Together', 'Never'),
        ('The safe savings or the risky investment?', 'Safe', 'Risky'),
        ('Retire to the mountains or the sea?', 'Mountains', 'Sea'),
        ('An early retirement, simple or a late one, lavish?', 'Early, simple', 'Late, lavish'),
        ('The house: old with character or new with no surprises?', 'Old, character', 'New, no surprises'),
        ('A fixer-upper project or a move-in-ready life?', 'Fixer-upper', 'Move-in ready'),
        ('City energy or small-town quiet?', 'City', 'Small town'),
        ('A home near your parents or near the best jobs?', 'Near parents', 'Near jobs'),
        ('Apartment with a view or house with a garden?', 'View', 'Garden'),
        ('The kitchen of your dreams or the bedroom of your dreams?', 'Kitchen', 'Bedroom'),
        ('A spare room for guests or one for hobbies?', 'Guests', 'Hobbies'),
        ('Renovate forever or move every few years?', 'Renovate', 'Move often'),
        ('A home that impresses or one that fits?', 'Impresses', 'Fits'),
        ('Minimal and tidy or full and lived-in?', 'Minimal', 'Lived-in'),
        ('Kids in the plan: definitely or let life decide?', 'Definitely', 'Let it decide'),
        ('Parent like yours did or the opposite?', 'Like mine', 'The opposite'),
        ('Kids close in age or years apart?', 'Close', 'Years apart'),
        ('One of you stays home or both keep working?', 'One stays home', 'Both work'),
        ('Raise them in the city or the suburbs?', 'City', 'Suburbs'),
        ('Strict household or open-door chaos?', 'Strict', 'Open-door'),
        ('Your children know everything about you someday or the edited version?', 'Everything', 'The edited version'),
        ('Family holidays: pack the kids or leave them behind?', 'Pack them', 'Leave them'),
        ('The aunt-and-uncle life or the parent life?', 'Aunt/uncle', 'Parent'),
        ('A house full of cousins or quiet just-us holidays?', 'Full of cousins', 'Just us'),
        ('The wedding: big party or small and sacred?', 'Big party', 'Small, sacred'),
        ('Vows from memory or read from the heart on paper?', 'From memory', 'On paper'),
        ('Marriage as a milestone or a formality?', 'Milestone', 'Formality'),
        ('Take their name or keep yours?', 'Take theirs', 'Keep mine'),
        ('A honeymoon far away or a first year at home together?', 'Honeymoon', 'First year home'),
        ('Videographer or photographer only?', 'Video', 'Photos only'),
        ('Write your own vows or the classics?', 'Our own', 'The classics'),
        ('Elope suddenly or plan for a year?', 'Elope', 'Plan a year'),
        ("Grow old gracefully or never admit it's happening?", 'Gracefully', 'Never admit it'),
        ('The porch swing or the cruise ship?', 'Porch swing', 'Cruise ship'),
        ('Old and opinionated or old and serene?', 'Opinionated', 'Serene'),
        ('A retirement full of travel or full of routine?', 'Travel', 'Routine'),
        ('Die first or be left behind?', 'Die first', 'Left behind'),
        ('Be the fun grandparents or the dependable ones?', 'Fun', 'Dependable'),
        ('Stories your grandkids retell or photos they keep?', 'Stories', 'Photos'),
        ('An obituary that lists jobs or one that lists loves?', 'Jobs', 'Loves'),
        ("A funeral that's a party or one that's a goodbye?", 'A party', 'A goodbye'),
        ('Leave money behind or spend it all on living?', 'Leave it', 'Spend it all'),
        ('Generational wealth or generational stories?', 'Wealth', 'Stories'),
        ("The inheritance you'd leave or the example you set?", 'Inheritance', 'Example'),
        ("Give to charity now or after you're gone?", 'Now', 'After'),
        ('Money talks had monthly or money fights had yearly?', 'Monthly talks', 'Yearly fights'),
        ("A will that's written or one that's 'someday'?", 'Written', 'Someday'),
        ('The dream you share or the dreams you cheer from the sidelines?', 'Shared dream', 'Sidelines'),
        ('A year off to travel or a year off to build something?', 'Travel', 'Build'),
        ('Fame for something you made or anonymity with everything you need?', 'Fame', 'Anonymity'),
        ('Learn the language or move anyway?', 'Learn it', 'Move anyway'),
        ('A bucket list you write down or one you keep in your head?', 'Write it', 'In my head'),
        ("Do the thing at 30 that you'd regret at 80?", 'Yes', 'Play it safe'),
        ('The anniversary tradition: same trip or new adventure?', 'Same trip', 'New adventure'),
        ('Renew the vows at 25 years or quietly celebrate?', 'Renew them', 'Quiet night'),
        ('Adopt a dog now or wait until the house is ready?', 'Now', 'Wait'),
        ("The risky move you'd make together or the safe one you'd make alone?", 'Risky, together', 'Safe, alone'),
        ('A legacy of kindness or of achievement?', 'Kindness', 'Achievement'),
        ('Grow together in faith or in doubt?', 'Faith', 'Doubt'),
        ('Take care of your parents as they age or fund their care?', 'Personally', 'Fund it'),
        ('The version of us at 70: best friends or still flirtatious?', 'Best friends', 'Still flirting'),
        ('Buy the boat or rent it twice a year?', 'Buy it', 'Rent it'),
        ('One life, lived boldly, or many lives, lived carefully?', 'One, boldly', 'Many, carefully'),
        ('The big move: their career or yours?', 'Theirs', 'Mine'),
        ('Follow each other anywhere or does a line exist?', 'Anywhere', 'A line exists'),
        ('A cabin you escape to or an apartment you never leave?', 'Cabin', 'Apartment'),
        ('Live abroad for love or stay home for family?', 'Abroad for love', 'Home for family'),
        ("The decade you're most excited for: this one or the next?", 'This one', 'The next'),
        ('A future documented in photos or in journals?', 'Photos', 'Journals'),
        ('Build a tradition or inherit one?', 'Build', 'Inherit'),
        ('Future Sunday mornings: market or mattress?', 'Market', 'Mattress'),
        ('The car: practical or a little reckless?', 'Practical', 'Reckless'),
        ('Grow old near your best friends or near your family?', 'Best friends', 'Family'),
        ('A second home someday: beach or mountains?', 'Beach', 'Mountains'),
        ('The dream kitchen table: full every Sunday or quiet most weeks?', 'Full', 'Quiet'),
        ('Would you move for them twice before they move once?', 'Yes', 'No'),
        ('A circle of close friends nearby or distance that keeps hearts fond?', 'Nearby', 'Distant, fond'),
        ('The someday first dance: rehearsed or improvised?', 'Rehearsed', 'Improvised'),
        ('Houseguests: always welcome or by invitation?', 'Always welcome', 'By invitation'),
        ('Live together before marriage or after?', 'Before', 'After'),
        ('Merge finances before the wedding or after?', 'Before', 'After'),
        ('Their dream needs the move: discuss it or follow it?', 'Discuss', 'Follow'),
        ('A year in the countryside or a year car-free in the city?', 'Countryside', 'Car-free city'),
        ('Be their teammate or their inspiration?', 'Teammate', 'Inspiration'),
        ('The future when it arrives: planned or improvised?', 'Planned', 'Improvised'),
        ('A dog before kids or after?', 'Before', 'After'),
        ('Write the letter to your future selves or keep it unsent?', 'Write and send', 'Unsent'),
        ('The garden you tend or the plants you keep alive?', 'The garden', 'Just keep them alive'),
        ("New Year's Eve in twenty years: party or pajamas?", 'Party', 'Pajamas'),
    ],
}
